### ISSUE TITLE
Can't set focus on input for survey-html-form

### ISSUE THREAD

**Issue by denisfitz57** [jspsych/jsPsych#1062]
I would like the participant to just enter their answers and advance without having to set focus by mouse click in the following timeline:
	var trialIndex = 0;
		for (trialIndex = 0; trialIndex < sequence.length; trialIndex++) {
		    var soundTrial = {
		        type: 'audio-keyboard-response',
		        stimulus: sequence[trialIndex] + ".wav",
		        autoplay: true,
		        choices: [],
		        trial_ends_after_audio: true
		    }
		    experimentTimeline = experimentTimeline.concat(soundTrial);
		    var form_trial = {
		        type: 'survey-html-form',
		        preamble: '<p> Please spell the word you just heard </p>',
				html: '<p> I heard: <input  name="word" type="text" spellcheck="false" autocomplete="off" /></p>'
		    };
		    experimentTimeline = experimentTimeline.concat(form_trial);
		}

adding autofocus to the input seems to have no effect

**Comment by becky-gilbert** [comment]
I agree this looks like a bug. I'm not sure what HTML you're using to create the text box, but I just tried with this:
```javascript
html: '<p>I heard: <input type="text" id="resp-box" name="response" size="10" autofocus/></p>'
```
This reproduced the problem: autofocus doesn't work and I get the console message: "Autofocus processing was blocked because a document already has a focused element."

This is something we should be able to fix in the form plugin. In the meantime, you can do this in your trial definition by adding an [`on_load` function](https://www.jspsych.org/overview/callbacks/#on_load) that focuses on the text box after it's been added to the screen. Just note that you'll need some way of grabbing the text box element, e.g. by giving it an ID in the HTML parameter like I did above. Then you can do this:
```javascript
on_load: function() {
    document.getElementById("resp-box").focus();
}
```

**Comment by denisfitz57** [comment]
I knew about focus() but couldn't figure out where to apply it.  Thank you!

**Comment by becky-gilbert** [comment]
No problem, and thanks for flagging this issue!

**Comment by chrisbrickhouse** [comment]
I've been looking through this plugin series, so I'd be willing to tackle this if there's no assignee yet.

**Comment by becky-gilbert** [comment]
@chrisbrickhouse yes please go for it! Thanks!

**Comment by becky-gilbert** [comment]
- [ ] update 6.2 docs with new autofocus parameter for survey-html-form plugin
