### ISSUE TITLE
Setting `post_trial_gap` after trial

### ISSUE THREAD

**Issue by jkrumbiegel** [jspsych/jsPsych#1235]
Hi, I really enjoy using the library so far, great work!

Is there a way to control the `post_trial_gap` given what happens in the trial? As far as I understand, passing a function will evaluate it at the start of the trial. My use case is a task after which a "too slow" notice should be shown immediately, if the participant didn't answer. So I want to set the `post_trial_gap` to zero in case there was no response.

**Comment by becky-gilbert** [comment]
Hi @jkrumbiegel, I don't think there's a way to do that because, like you said, all of the trial's dynamic parameters will evaluate at the _start_ of the trial (with the exception of [event-related callback functions](https://www.jspsych.org/overview/callbacks/)). A clumsy workaround would be to use a blank 'trial' as your ITI instead of the `post_trial_gap`, so that you can control when/whether the ITI occurs and its duration, based on what happened during the last trial. And if you always want an ITI of the same duration before the start of every trial, then you could just put the 'too slow' message inside of a conditional that comes directly after the main trial, and then have the ITI trial after the too slow conditional, like this:
```javascript
    var trial = {
        type: 'html-keyboard-response',
        stimulus: 'Enter a key!',
        choices: jsPsych.ALL_KEYS,
        trial_duration: 1000
    };
    var too_slow = {
        type: 'html-keyboard-response',
        stimulus: '<span style="color: red;">Too slow!</span>',
        trial_duration: 2000
    };
    var too_slow_conditional = {
        timeline: [too_slow],
        conditional_function: function() {
            var last_rt = jsPsych.data.getLastTrialData().values()[0].rt;
            if (last_rt == null) {
                return true;
            } else {
                return false;
            }
        }
    };
    var iti = {
        type: 'html-keyboard-response',
        stimulus: '',
        choices: jsPsych.NO_KEYS,
        trial_duration: 500
    };

    jsPsych.init({
        timeline: [trial, too_slow_conditional, iti, trial, too_slow_conditional, iti],
        on_finish: function () {
            jsPsych.data.displayData();
        }
    });
```
I hope this helps!

**Comment by jkrumbiegel** [comment]
Hi Becky, the approach with the full trial and conditional timeline is exactly how I'm currently solving the problem, it's just not a very clean solution. Given that the post_trial_gap happens after the trial it seemed sensible to me that there should be some way of changing it during the trial, before the waiting period is initiated.

Basically, I think all trial aspects that only become relevant after the trial body is over, should have a way of being changed if one doesn't want to rely on workarounds with additional trials etc. Something like a `deferredVariable()` function that is called at trial end to resolve it's value

**Comment by becky-gilbert** [comment]
Sorry @jkrumbiegel, I once again mistook this for a discussion post question rather than an issue! Oops 😬 Thanks for the suggestion - I agree this would be a much cleaner solution.

@jodeleeuw what do you think about adding the ability to set the `post_trial_gap` value during/after the trial, so that trial data can be used to determine the value? (And the same for any other parameter values that aren't needed until the end of the trial, although I can't think of any others apart from `data`, which can already be modified in the `on_finish` function).

**Comment by jodeleeuw** [comment]
I suppose we could add a second optional parameter to `on_finish` that allowed modifying this parameter value in place. I'm a little hesitant to add the complexity for the single-use case. I'm trying to come up with other cases where the suggestion of a `deferredVariable` could be applied. @jkrumbiegel any ideas?
