### ISSUE TITLE
Fixing video preloading causes CORS error when opening file directly

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#1258]
**Problem:**
Previously video files were not automatically preloading. Now that this has been fixed (#1171), the automatic video preloading is blocked when opening HTML files directly due to CORS policy, which prevents the experiment from running. The experiment does run when preloading does not occur - the video file is successfully retrieved when the trial begins. To fix this, we need some way of determining whether or not to automatically preload the video files.

**Proposed solution:**
In jspsych.js, [detect whether the HTML file is running via the file:// protocol](https://stackoverflow.com/questions/3920892/how-to-detect-if-a-web-page-is-running-from-a-website-or-local-file-system), and if so, disable the features that cause CORS errors: WebAudio and video preloading. 
There also needs to be a console message when this occurs to alert the researcher, since by default the file will run differently when opened in the browser as a file vs hosted on a server. 
And there should be an option in `jsPsych.init` to prevent this from happening - something like `adapt_to_file_protocol: false`.

**Questions:**
1. If the file protocol is detected, would this override any `jsPsych.init` options that are explicitly set to contradict it, i.e., `use_webaudio: true` and `preload_videos: ["video.mp4"]`?
2. Better name for the jsPsych.init parameter to control this feature?

**Comment by jodeleeuw** [comment]
Thanks for opening this issue to track it!

I think we *should* override options in `jsPsych.init`, even if they are explicitly set. My first inclination was to not do this, but then I thought more about the developer's experience. It would be annoying to have to take out `use_webaudio` and `preload_videos` parameters just because you are testing locally if you want those parameters in when you are running on a server. It'll also be less confusing for new users if things just work. We want to balance this with ensuring that full control is possible, but I think the `adapt_to_file_protocol` option works. 

Other ideas for the parameter name:

* `cors_safe`
* `cors_safe_mode`
* `local_testing_environment`
* `override_safe_mode` (would be `false` by default unlike the other parameters)
* `override_cors_safe_mode` (also `false` by default)

**Comment by becky-gilbert** [comment]
Thanks for the feedback Josh! Totally agree with your points about overriding the other `jsPsych.init` settings.

WRT the parameter name, I wondered if this is something that would only every be used to fix CORS issues or if it would potentially be used for other reasons? In the latter case I suppose it would be better to have a more generic name that doesn't include CORS. So my vote is for `override_safe_mode` (default is `false`).

And I like `local_testing_environment` but that might be confusing since some people will be running their experiments on local servers. So I think the distinction is really server vs non-server (file), rather than local vs remote, right?
