### ISSUE TITLE
Relative links not working on overview of plugins page

### ISSUE THREAD

**Issue by jackdolgin** [jspsych/jsPsych#1265]
I wasn't sure how to fix it (hence no pull request), but when I click the links in the table on https://www.jspsych.org/plugins/overview/ I get taken to a page that doesn't exist. It looks like `overview/` is getting added to each url accidentally.

**Comment by becky-gilbert** [comment]
You're right, thanks for flagging this @jackdolgin! We'll get this fixed in the next release.

p.s. I'm not totally sure about how to fix this either, but I _think_ the links need to go up one level with "../" so that the plugin page name gets added onto "h<span>ttp</span>s://www.jspsych.org/plugins" instead of being appended onto the current page ("ht<span>tp</spam>s://www.jspsych.org/plugins/overview"), e.g. 

Plugin \| Description
------ \| -----------
\[jspsych&#8209;animation](../jspsych-animation) \| Shows a sequence of images at a specified frame rate. Records key presses \(including timing information) made by the subject while they are viewing the animation.
