### ISSUE TITLE
jsPsych.startTime(); is undefined

### ISSUE THREAD

**Issue by mrzdcmps** [jspsych/jsPsych#1287]
Hi,
I am trying to add a timestamp to the experiment's data, but the function "jsPsych.startTime();" returns "undefined".
Date(); is working however.

**Comment by becky-gilbert** [comment]
Hi @mrzdcmps, is it possible that `jsPsych.startTime()` is being called before the experiment starts, i.e. when the page first loads? This would happen if it's in the main script rather than inside of a function (like a [dynamic parameter](https://www.jspsych.org/overview/trial/#dynamic-parameters) or [callback function](https://www.jspsych.org/overview/callbacks/)). I've just tried this and it works for me:
```javascript
var trial = {
    type: 'html-keyboard-response',
    stimulus: function() {
        return "Start time is: " + jsPsych.startTime();
    }
}

jsPsych.init({
    timeline: [trial]
});
```
I don't have any other ideas about why you're getting "undefined", but feel free to post the relevant bit of code if you want more help figuring it out.

**Comment by mrzdcmps** [comment]
@becky-gilbert That's it - thanks!
