### ISSUE TITLE
exclude Participants Based on Browser (not features but type) and device

### ISSUE THREAD

**Issue by lawero** [jspsych/jsPsych#1325]
As the title say I need to run an experiment only through Chrome and personal computer (not smartphone or tablet). There is a way to obtain it?

Thx!

**Comment by becky-gilbert** [comment]
Hi @lawero, sorry for the slow response. Not sure if you've already found a solution for this? In case you haven't - you can check out [this pull request](https://github.com/jspsych/jsPsych/pull/641) that shows how to exclude mobile devices. If you look in the 'files changed' tab, you can find the relevant changes, which is just the code in the `if` statement in jspsych.js. That `if` statement will return `true` if the person is using a mobile device and `false` if not. As we note in the discussion for this pull request, the regular expression (regex) used to check for mobile devices might be out of date, so you could search online for a more up-to-date mobile device regex detection and use that instead.

Detecting the use of Chrome can be done in a similar way. You can search for something like "user agent string detect browser" and try to find a recent solution, since user agent strings change over time. [Here's one method I found for browser detection](https://www.geeksforgeeks.org/how-to-detect-the-user-browser-safari-chrome-ie-firefox-and-opera-using-javascript/) (not sure if it works!). And here's some more [general information about using the user agent string to detect browsers/devices](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent) that you might find helpful.

**Comment by lawero** [comment]
Thank you very much!
Now I close this issue because this is for sure the answer I was looking for but I'll leave soon an update with my implementation.

**Comment by becky-gilbert** [comment]
Great! @lawero yes please feel free to update this thread with your implementation, in case other researchers want to do the same thing. Thanks!

**Comment by lawero** [comment]
My solution for checking the browser is quite easy but I think it's quite raw too. I need to know just if the browser is Chrome and I tested the code only with these three (see code).

The exclusion for the mobile already works for me (I tested with just two phones).

Of course it's really easy for an user to trick this exclusion controls but for me this is far to be important. It's more a strong reminder for the user to avoid other browser than a really imposition.
```
  // CHROME
  // Checks adapted from https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser
  if(typeof exclusions.onlychrome !== 'undefined' && exclusions.onlychrome) {
    var isChrome = !!window.chrome && navigator.userAgent.indexOf("Edg") == -1;

        /*
        var isChrome = !!window.chrome && navigator.userAgent.indexOf("Edg") == -1;
        console.log("chrome:"+isChrome);
        var isFirefox = typeof InstallTrigger !== 'undefined';
        console.log("firefox:"+isFirefox);
        var isEdgeChromium = !!window.chrome && (navigator.userAgent.indexOf("Edg") != -1);
        console.log ("edge:"+isEdgeChromium)
        */
    if(!isChrome) {
      clear = false;
      var msg = '<p>This is not Chrome.</p>';
      core.getDisplayElement().innerHTML = msg;
      fail();
      return;
    }
  }
```
