### ISSUE TITLE
Move preloading behavior to a plugin

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#1351]
Following ideas from #1234:

> I'm also wondering if part of the solution here is to convert the preloading features into a plugin and move them out of `jspsych.js`. This might make it easier to parameterize, and also allows for easier customization by researchers. It would also provide a built-in solution to perform partial caching of materials throughout the experiment. We've seen that feature needed in many cases, e.g. #724. 

> The downside is that automatic preloading wouldn't be as easy to support. But we could still populate a list of media to preload at the start of the experiment and allow the plugin to access that list. So the experience might be:

```js
var preload = {
	type: 'preload',
	auto_preload: true,
	images: [...],
	audio: [...],
	video: [...],
	show_progress_bar: true,
	loading_message: '<div>whatever html here.</div>',
	show_detailed_errors: true,
	max_load_time: 60000
}
```

**Comment by becky-gilbert** [comment]
Great idea. I agree that this will help with parameterization and flexibility in terms of when exactly to load particular files during the experiment.

> The downside is that automatic preloading wouldn't be as easy to support. But we could still populate a list of media to preload at the start of the experiment and allow the plugin to access that list. 

I'm not clear on how exactly this would work. In the case where all stimuli files can be auto preloaded, does this mean the researcher adds the preload trial to the timeline but doesn't need to pass in any image/audio/video arrays (i.e. these will be undefined)? Or do they pass empty arrays? Or use a new function like `jsPsych.getAutoPreloadList` for the image/audio/video parameter values?

At the risk of overcomplicating this plugin - would it be possible to add the option for files to be loaded in the background? This something researchers have asked about (#961, #742). The plugin would initiate the file loading and then, depending on this background-loading parameter, either show the progress bar/message (the existing behavior) or end the preload 'trial' to initiate the next event in the timeline. It would require some kind of flag or callback to let the experiment know whether/when the files have successfully loaded, which could then be used to either continue the experiment (at the point when the files are needed), continue waiting for the files to load (if the max_load_time has not been reached), or show an error message (if max_load_time is reached). If this sort of background-loading parameter is possible, perhaps it could wait to be added later so as not to hold up progress on moving the preloading into a plugin.

**Comment by jodeleeuw** [comment]
I took a first pass at this in the `feature-preload-plugin` branch. It involved a bunch of changes to core jsPsych code.

- Removes `autoPreload` method from `jsPsych.pluginAPI`
- Removes all preload-associated parameters from `jsPsych.init()`
- Adds a method `jsPsych.getAutoPreloadList` to `jsPsych.pluginAPI`. This method takes a timeline description and returns an object with `{images, video, audio}` properties. Each property is an array with the paths to files that need to be preloaded.

As I was describing this, I realized that there's a problem with my approach, though. I was expecting to be able to do something like this:

```js
var timeline = [];

var preload = {
	type: 'preload',
	auto_preload: timeline
}

var image_trial = {
	type: 'image-keyboard-response',
	stimulus: 'img/foo.png'
}

timeline.push(preload, image_trial);

jsPsych.init({
	timeline: timeline
});
```

This doesn't work, though, because the reference to `timeline` in `auto_preload` is circular and it triggers a never-ending copying of that parameter.

So I need to rethink the design here a bit. My hope was that the `auto_preload` parameter could be more than just a boolean, so that folks could automatically preload a *portion* of the experiment at a time if desired. But I'm not sure how to do that when the plugin itself exists in the timeline. Note that the code that triggers the recursive copying is not plugin-specific code. My initial idea of just adding a safety check inside the plugin code won't cut it.

**Comment by becky-gilbert** [comment]
How about allowing the `auto_preload` parameter to take _etiher_ a boolean (where `true` means automatically preload the whole timeline) _or_ a subset of trials. (Or separating these into two parameters). 

Using a boolean would eliminate the circular `timeline` reference problem, but would mean that the preload plugin code needs to be able to access the whole timeline via a jspsych.js function.
```javascript
var timeline = [];

var preload = {
	type: 'preload',
	auto_preload: true
}

var image_trial = {
	type: 'image-keyboard-response',
	stimulus: 'img/foo.png'
}

timeline.push(preload, image_trial);

jsPsych.init({
	timeline: timeline
});
```
And then you could do this for auto-preloading a portion of the experiment:
```javascript
var timeline = [];

var image_trial_1 = {
	type: 'image-keyboard-response',
	stimulus: 'img/foo.png'
}

var image_trial_2 = {
	type: 'image-keyboard-response',
	stimulus: 'img/bar.png'
}

var preload_1 = {
	type: 'preload',
	auto_preload: [image_trial_1]
}

var preload_2 = {
	type: 'preload',
	auto_preload: [image_trial_2]
}

timeline.push(preload_1, image_trial_1, preload_2, image_trial_2);

jsPsych.init({
	timeline: timeline
});
```

**Comment by jodeleeuw** [comment]
Great ideas. I decided to make `auto_preload` strictly boolean, and added an additional parameter called `trials` that can take an array of trial descriptions to preload from.

This is now on the `feature-preload-plugin` branch. I added two test files, one for the new `getAutoPreloadList` method and another for the plugin. Can you work on expanding the test suite, doc updates, etc.? Also, feel free to add the background loading feature if you want to take a stab at that.

**Comment by becky-gilbert** [comment]
Got it - will do!

**Comment by becky-gilbert** [comment]
@jodeleeuw two questions about this preload plugin:
1. What should the plugin's behavior be if preloading fails? Right now the preload trial ends the same way, regardless of whether preloading fails or succeeds. Do we want to replicate the old preloading behavior, where if preloading fails, the experiment stops with a (parameterized) error message? If not then I think the trial data should contain a boolean `success` variable, so that the researcher can access this data in a conditional node to continue the experiment or do something else.
2. I noticed a typo in the current version: the plugin uses `jsPsych.pluginAPI.preloadAudio` but the function name is `jsPsych.pluginAPI.preloadAudioFiles` in jspsych.js. Would you prefer to keep the `preloadAudioFiles` function name (e.g. for backwards compatibility) or switch to `preloadAudio` to be consistent with the `preloadImages`  and `preloadVideo`  function names?

**Comment by jodeleeuw** [comment]
I like the `success` variable in the data. Maybe also a list of `failed_images`, `failed_audio`, and `failed_video` that gives the path to each failed load resource?

Good catch on the `preloadAudio`! I think this is a good moment to make things consistent.

**Comment by becky-gilbert** [comment]
Sorry @jodeleeuw, another question about this plugin: What should the `show_detailed_errors` parameter do? Show error info in the console, or on the page as in #1234? Something else?

At the moment the preload plugin doesn't actually stop the experiment when loading fails - instead it ends the trial with `success: false`, and we're expecting the researcher to check/catch any errors after the trial ends. So if the errors should be shown on the page (as in #1234), then I'm wondering what should happen if preloading fails and `show_detailed_errors` is `true`. Does that mean that the preload trial shouldn't end so that the user can read the error info on the page? Or should it just wait for some (hard-coded or parametrized) duration before continuing?

**Comment by becky-gilbert** [comment]
I pushed some changes to this branch, including an [example HTML file](https://github.com/jspsych/jsPsych/blob/feature-preload-plugin/examples/jspsych-preload.html). I might be missing something, but this plugin doesn't feel as user-friendly as it could be. I think most researchers will want to do different things depending on whether or not the preloading was successfully, so I'm wondering if we could add some parameters to optionally handle this in the plugin, rather than forcing people to use dynamic parameters or conditional nodes after a preload trial. Could we do something like this?
```javascript
var preload_trial = {
    type: 'preload',
    auto_preload: true,
    load_message: 'Please wait while the files load...',
    continue_after_error: false,
    error_message: 'The experiment failed to load.',
    error_message_duration: null,
    show_detailed_errors: true
};
```
If `continue_after_error` is `true` then the preload trial ends regardless of whether the files load successfully or fail to load after `max_load_time` (this is the behavior that is currently implemented). The researcher can then use the trial data to determine what happens next.
If `continue_after_error` is `false` then the trial shows the `error_message` (along with detailed error messages if `show_detailed_errors` is `true`) for the `error_message_duration`. Or if `error_message_duration` is `null`, the trial wouldn't end (which I think is the same behavior that currently exists with preloading via `jsPsych.init`?).

**Comment by jodeleeuw** [comment]
@becky-gilbert this is great feedback. I think I was focused on getting the core mechanics in and didn't think hard enough about what to do when preloading fails. 

I think your solutions are great. One additional idea that @javidalpe suggested is having an error event handler that could be called. Maybe an `on_error` parameter with an informative `error` parameter?

**Comment by becky-gilbert** [comment]
> I think I was focused on getting the core mechanics in and didn't think hard enough about what to do when preloading fails.

No problem at all! I knew you'd just made a start on this and hadn't finished, just wanted to make sure that I understood your plans for this plugin 😃 

> One additional idea that @javidalpe suggested is having an error event handler that could be called. Maybe an on_error parameter with an informative error parameter?

Sounds good! Would this `on_error` parameter be _in place of_ or _in addition to_ the other error-related parameters that I suggested (`continue_after_error`, `error_message`, `error_message_duration`, `show_detailed_errors`)? These latter parameters all produce behavior that could be done via an `on_error` function. So including all of these things means there would be more than one way to do things, but also provides both convenience and flexibility for the researcher. 

We'd also need to figure out the correct order of execution for the `error_message` parameter and `on_error` function. I think that I would have the plugin show the parameterized error message first, then immediately call the `on_error` function, then continue waiting for the `error_message_duration` before ending the trial. 

Is this at all what you were thinking? And do the specifics sound ok? Or maybe you'd prefer that everything happen through an `on_error` function?

**Comment by jodeleeuw** [comment]
I like the parameters you suggested since they cover the most common use cases. The `on_error` would add additional flexibility, and would allow services like cognition.run to attach an error handler automatically.

> We'd also need to figure out the correct order of execution for the `error_message` parameter and `on_error` function. I think that I would have the plugin show the parameterized error message first, then immediately call the `on_error` function, then continue waiting for the `error_message_duration` before ending the trial.

Yes, this sounds right to me. 

Is the idea behind `error_message_duration` that someone might want to show an error but then continue anyways? I'm trying to think of a use case where I'd want to set the duration, but then continue on after the message. I'm struggling with a lack of imagination. Do you have a use case in mind? If not, maybe we don't need this parameter, and the message just stays up?

**Comment by becky-gilbert** [comment]
Yeah now that you mention it, there's probably not a good use case for showing the error message and then continuing on with the experiment. And if someone wants to do that then it can still be done via the `on_error` function. I'll scrap the `error_message_duration` parameter. 

And maybe instead of the `continue_after_error` parameter name, we should just call it `show_error_message`. If `true`, if there's an error then the experiment stops with the `error_message`. If `false`, the trial ends regardless of success/failure, but this info can still be obtained from the trial data, and if there's an error then the `on_error` function would still be called.

> The on_error would add additional flexibility, and would allow services like cognition.run to attach an error handler automatically.

Does this mean that the researcher wouldn't be able to specify a custom `on_error` trial parameter when one is automatically attached by a service like cognition.run, because the trial object would contain two parameters with the same name? Is there a way to pass multiple `on_error` functions into the plugin? I feel like I'm probably missing something really obvious here 😕

**Comment by jodeleeuw** [comment]
> And maybe instead of the continue_after_error parameter name, we should just call it show_error_message. If true, if there's an error then the experiment stops with the error_message. If false, the trial ends regardless of success/failure, but this info can still be obtained from the trial data, and if there's an error then the on_error function would still be called.

I think I prefer `continue_after_error` here because it's clear what it does for the flow of the experiment. I'm worried that `show_error_message` doesn't make it clear that the experiment will stop on an error. I realize that it's not clear whether a message will show with `continue_after_error` but I think that's the less important consideration for a researcher. 

> Does this mean that the researcher wouldn't be able to specify a custom on_error trial parameter when one is automatically attached by a service like cognition.run, because the trial object would contain two parameters with the same name? Is there a way to pass multiple on_error functions into the plugin? I feel like I'm probably missing something really obvious here 😕

I don't think you are missing anything. That's a good point. I was imagining that cognition.run might just stick a preload plugin to the timeline by default to mimic their current behavior. But I guess that is something for @javidalpe and team to decide! Either way, I think it'll be OK if we only have one error handler possible. We could also add an `on_error` handler to `jsPsych.init` and call both the plugin copy and the `jsPsych.init` copy...

**Comment by becky-gilbert** [comment]
Got it - thanks! I think I can finish up the implementation/docs/examples now, and then we can make further tweaks if necessary.

**Comment by becky-gilbert** [comment]
Quick question @jodeleeuw: the `auto_preload` method doesn't seem to work with a nested timeline, like this:
```javascript
var preload = {
  type: 'preload',
  auto_preload: true
}

var trial = {
  type: 'image-keyboard-response',
  render_on_canvas: false,
  timeline: [
    {stimulus: 'img/foo.png'}
  ]
}

jsPsych.init({
  timeline: [preload, trial]
);
```
Is that what you'd expect?

**Comment by jodeleeuw** [comment]
No, I intended for nested timelines to be covered. I can work on the fix soon. Did you add a test case to cover this?

**Comment by becky-gilbert** [comment]
Yep the code above is from my test. The tests for timelines in objects with conditional and loop functions are working. I can push my changes to the branch tomorrow if that helps.

**Comment by jodeleeuw** [comment]
@becky-gilbert I think this is fixed now. This was an error because my function for finding preload targets didn't account for cases where the `type` parameter was inherited from the parent timeline. This was probably broken in previous jsPsych versions, but never noticed...

**Comment by becky-gilbert** [comment]
Ok thanks! 
By the way I noticed that a bunch of my preload plugin tests aren't written very well. I've fixed them and will push an update soon.

**Comment by becky-gilbert** [comment]
I think this is about done.

I added as many tests that I could think of to the test.js file. However I did put some of the `expect` functions inside of `setTimeout` functions because I wasn't sure how else to wait until the preload trial stopped with an error before calling `expect`. In some cases I could've put them inside of callback functions, but I worry that it's possible that callbacks won't ever be called, in which case I think the test would pass without ever testing anything. For instance, if preloading fails and `continue_after_error` is `false` , then the trial never actually ends and therefore the trial's `on_finish` function is never called (which I think is what we want to happen, right?). 

Another option is to add a parameter for a function that should be called if/when the trial stops with an error. Right now the plugin has `on_success` and `on_error` parameters, but these are called after _each file_ loads/fails or when the loading times out.

**Comment by jodeleeuw** [comment]
> For instance, if preloading fails and continue_after_error is false , then the trial never actually ends and therefore the trial's on_finish function is never called (which I think is what we want to happen, right?).

Yeah, that seems right to me!

One option might be to use [mock timers in Jest](https://jestjs.io/docs/en/timer-mocks). But I've also found situations in the test suite where mocks don't work and I've used `setTimeout`. As long as the timeout is short it's not a big deal.

**Comment by becky-gilbert** [comment]
Great, thanks!

Ah, I didn't know about mock timers. That looks like what I want. The timeouts are pretty short, but there's a lot of them and it slows things down, so I'll see if I can fix it quickly.

**Comment by becky-gilbert** [comment]
@jodeleeuw question about a merge conflict between this `feature-preload-plugin` branch and master. 

On master, the `addNodeToEndOfTimeline` function has a `preload_callback` argument, which was meant to auto preload any stimuli from the new timeline:
https://github.com/jspsych/jsPsych/blob/9bfeaff84a2044789f9efa47fc4532ee0241e533/jspsych.js#L352-L361

On the `feature-preload-plugin` branch, the callback argument is gone (because we got rid of the `jsPsych.pluginAPI.autoPreload` function and `auto_preload` parameter in `jsPsych.init`):
https://github.com/jspsych/jsPsych/blob/fbd9e4ca8583174da1a483c8e59b54e1597e2860/jspsych.js#L318-L320

So after merging, this timelines test fails because the test uses a callback:
https://github.com/jspsych/jsPsych/blob/9bfeaff84a2044789f9efa47fc4532ee0241e533/tests/jsPsych/timelines.test.js#L471-L495

Based on your test, I'm guessing that the `addNodeToEndOfTimeline` function should still allow an optional callback argument, but just not try to do any auto-preloading:
```js
core.addNodeToEndOfTimeline = function(new_timeline, callback){
  timeline.insert(new_timeline);
  if(typeof callback !== 'undefined'){
    callback();
  }
}
```
Is that right?

**Comment by jodeleeuw** [comment]
I think we can just get rid of the callback completely at this point since adding the node to the timeline is synchronous. Does that seem right to you?

**Comment by becky-gilbert** [comment]
Yes! That definitely makes more sense 🤦 I'll remove the failing test.
