### ISSUE TITLE
Images stop appearing with html-image-keyboardresponse plugin

### ISSUE THREAD

**Issue by marco2gandolfo** [jspsych/jsPsych#1476]
Dear all,

I am encountering an odd issue.
I am using a task where I ask people to respond to images with html-image-keyboard-response.
The image is on screen for 250mseconds and it is called with jsPsych.timelineVariable('stimulus') inside a trial procedure.

I am sure that my code works, because this problem presents only sometimes when I ran the experiment. Most of the times indeed, the experiment runs smoothly. However, in few occasions, particularly if I take a long break, images stop appearing.

I should say that this problem presented only since I switched to JsPsych 6.2 and that I preload all the images beforehand. Also, it may be relevant to say that my images are in .png format. 

My suspect is that this is a caching problem but I could not successfully reproduce consistently this issue so I cannot be sure. 

Did anybody else had similar issues?

Many thanks for your help, as usual!

Cheers,
Marco

**Comment by becky-gilbert** [comment]
Hi @marco2gandolfo, if you're preloading all of the files (and you've checked that the preloading is definitely working), then this does sound like it might be a caching problem. Are you using lots and/or large image files? If so, the browser might be removing some files from the cache after a while. Here are some other Discussion posts that explain this problem and include some possible solutions:
Cache limit  #1254
How to fix audio playback glitches? #1066 
Preloading set of images per trial #724

And have you seen Discussion post #1304 and this related issue #1305 about images not appearing in the v6.2 image-* plugins? This happens when `render_on_canvas` is `true` (the default) and when the image files aren't available when the plugin tries to draw them onto the canvas element. In v6.2, you can add `render_on_canvas: false` to your image-keyboard-response trial, which fixes this problem. Also, we've now fixed the problem with canvas rendering on the master branch, so another option is to use the master branch version of the image-keyboard-response plugin: https://github.com/jspsych/jsPsych/blob/master/plugins/jspsych-image-keyboard-response.js But these changes just help to ensure that the images will be presented as soon as they're loaded by the browser. Given your relatively short presentation times, your experiment may still entirely skip some images if the image doesn't finish loading within the 250 ms trial duration. So the biggest difference will come from fixing the image preloading/caching issues using the methods described in the Discussion threads above.

One final suggestion: if you're testing your experiment with the developer tools open, just double check that the Disable Cache box isn't ticked.
![devtools_cache](https://user-images.githubusercontent.com/9041788/107273785-61e8eb00-6a04-11eb-85ab-2e5f123b2fee.PNG)

**Comment by marco2gandolfo** [comment]
Dear Becky,

Thanks so much for giving me so much points to dig into!
My images are about 700 to 800 kb each and I am preloading a total of ~260 images. 
They are not exceptionally big but they are indeed the biggest size I ever presented! 
I checked and the "disable cache" button is not ticked :).

In this next few days I will dig into the points you raised and get back to you.

Many thanks, as usual, for your kind help.

Cheers,
Marco

**Comment by stefanoanzani** [comment]
Hi,
I'm here because I was encountering the same bug while following along the reaction time tutorial experiment. I started noticing it in part 6, but maybe was already there in part 5.
`render_on_canvas: false` did not solve the problem, but preloading the images did. I don't know if the next release (6.3) will fix it, but encountering the bug in the tutorial was really confusing. Maybe it could help either mentioning the bug and the solution, or rather suggesting to download the same version used in the tutorial (6.0.5) while following along to avoid any problem?

I'm sorry, maybe this is not super relevant here, I'm new to github and i'm not sure if it would be better to open a new issue, rather than commenting here.

**Comment by jodeleeuw** [comment]
@stefanoanzani thanks, that's a great point. We are updating the tutorial for 6.3, which will be out within the next 1-3 days.
