### ISSUE TITLE
Error handling when video files don't exist

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#1537]
See #1530 for rationale.

**Comment by chrisbrickhouse** [comment]
The preloadVideo function in core takes an error callback that gets run if the AJAX request for the file results in 404 (see around 2735 in core). The problem (I think, need to debug more) is that if that error callback is undefined, any error response gets thrown out and the program keeps running resulting in the behavior in #1530 since the plugin doesn't know that something is wrong.

The two possible solutions would be to edit core so that these errors bubble up without a callback, or have extensions explicitly provide callbacks for errors. I have a slight preference for the first one. If not handled, it lets the user know that something's wrong rather than silently proceeding (at the very least the console should probably log a warning). For plugins, it allows errors to be handled using try-catch blocks which helps with readability.

Thoughts?

**Comment by chrisbrickhouse** [comment]
Has this been fixed already? In testing, the console throws warnings whenever resources don't exist, so I can't replicate the behavior in #1530. I think this can be closed unless an experiment-stopping error is better than the warnings already thrown (which I doubt).
