### ISSUE TITLE
jsPsych.pluginAPI.compareKeys handling null keys

### ISSUE THREAD

**Issue by klanderson** [jspsych/jsPsych#1577]
Hi, just trying out jsPsych 6.3.0 (great update btw), and noticed that `jsPsych.pluginAPI.compareKeys` fails when one of the keys is null. Would you consider allowing null inputs? So the function would return `false` if any one input is null and `true` if both are null.

I'm handling null responses now as follows:

```
if (data.response != null) {
    data.hit = jsPsych.pluginAPI.compareKeys(data.response, data.correct_response);
} else {
    data.hit = false;
}
```

**Comment by becky-gilbert** [comment]
Hi @klanderson, thanks for the feedback, and for explaining the use case for `null` arguments here. This sounds like a very reasonable change to me. 
@jodeleeuw I think this is a quick fix so I'm happy to do it, if you want to add this to 6.3.1?

**Comment by becky-gilbert** [comment]
Hi @klanderson, I've now changed this on the master branch version of jspsych.js, so `jsPsych.pluginAPI.compareKeys` will handle `null` values in the next release.

As of right now there haven't been any other changes to the master branch jspsych.js file since the 6.3.0 release on Feb 21. This means you could replace your v6.3.0 jspsych.js file with the master branch version to get this new functionality, without risking any compatibility issues. If you do this, it might be a good idea to double-check the [jspsych.js commit history](https://github.com/jspsych/jsPsych/commits/master/jspsych.js) before downloading, to see if there have been any other changes made in the meantime.

**Comment by klanderson** [comment]
Thank you!
