### ISSUE TITLE
Link to live examples from the docs.

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#164]

**Comment by becky-gilbert** [comment]
I was thinking about this while working on the docs for 6.2 It'd be nice to have live examples alongside the code examples in the plugin docs. Or even just screenshots/gifs, if live demos are too tricky to set up.

Where would we host the live demos, and how would they be integrated with the docs? iframes in the docs pages?

**Comment by becky-gilbert** [comment]
I've done this for a few plugin docs pages (animation and audio-* plugins) and put it in the [docs-demos branch](https://github.com/jspsych/jsPsych/tree/docs-demos). Demo HTML files are in docs/plugins/demos, and use the jsDelivr CDN to get all of the jsPsych files. These are presented in an iframe embedded on the markdown docs pages, under the example code. Seems to work well. Feedback welcome!

**Comment by becky-gilbert** [comment]
Just realized that I should add a "Start demo" button to the start of each demo, otherwise they just start automatically when the docs page loads.

**Comment by kurokida** [comment]
I'm happy to help. But, I am not good at writing in English. Thant's why,  I think someone should check my writing.

**Comment by jodeleeuw** [comment]
Thanks @kurokida! I think there's relatively little English writing involved here, at least for the conversion that @becky-gilbert has implemented. See [my comment here](https://github.com/jspsych/jsPsych/discussions/1923#discussioncomment-918361) for more details.

**Comment by becky-gilbert** [comment]
Thanks very much @kurokida! Josh is right that there isn't much English writing - it's mostly programming. But I can also help with any language editing when I review pull requests 😀

**Comment by becky-gilbert** [comment]
Hi @kurokida, @alexburm, and anyone else interested in helping out with this. I realize you both have experience with Git/Github already, but I'm going to include some extra guidance here for anyone else who may be new to this :smiley:

First, make sure you fork the jsPsych repository, if you haven't already (here's [how to fork a repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo), in case you've never done this before). Once you have a local copy of the jsPsych repo, switch to the docs-demo branch (`git checkout docs-demo`).

Once you're on the docs-demo branch of your jsPsych forked repo, you can start editing the plugin documentation pages, which are the markdown (.md) files located in docs/plugins, and the demo HTML files, which are in docs/plugins/demos. 

In the plugin docs pages, we need help re-formatting the Examples sections for all of the plugins. I've already done this for 4 plugins:
- [jspsych-animation.md](https://github.com/jspsych/jsPsych/blame/docs-demos/docs/plugins/jspsych-animation.md#L28-L50)
- [jspsych-audio-button-response.md](https://github.com/jspsych/jsPsych/blame/docs-demos/docs/plugins/jspsych-audio-button-response.md#L37-L74)
- [jspsych-audio-keyboard-response.md](https://github.com/jspsych/jsPsych/blame/docs-demos/docs/plugins/jspsych-audio-keyboard-response.md#L35-L73)
- [jspsych-audio-slider-response.md](https://github.com/jspsych/jsPsych/blame/docs-demos/docs/plugins/jspsych-audio-slider-response.md#L42-L80)

You can use the Examples sections in the files above as templates. For each of the code snippets in the Examples section, we need a corresponding demo HTML file to go in the /demos folder. If there are multiple code examples for a given plugin, then just add numbers to the end of the demo's file name.

For the demo HTML files, again you can use the [existing demo files](https://github.com/jspsych/jsPsych/tree/docs-demos/docs/plugins/demos) as templates. There's some extra stuff in these files, in addition to the demo trial code shown on the docs page. For instance, the demo should include media preloading (if necessary), a 'Run demo' trial at the start, the main demo trial, a 'show data' trial, and a loop that repeats the main demo and data trials if the 'Repeat demo' button is clicked. You may also want to make some CSS changes to get the demo content to fit inside of the iframe.

The jsPsych files are loaded using the jsDelivr CDN (content delivery network), which is why the file sources start with: "https://cdn.jsdelivr.net/gh/jspsych/jsPsych@6.3.1/". You can use the CDN to get any plugins and media files that were part of the 6.3.1 release. If you want to use any other media files, you can add them to img/sound/video subfolders inside of /demos.

As you make changes on your local docs-demos branch, you'll need to [commit them](https://github.com/git-guides/git-commit) locally (`git add <filename>`, then `git commit -m '<commit message>'`). Then, [push the changes](https://docs.github.com/en/get-started/using-git/pushing-commits-to-a-remote-repository) to your forked repository on Github, e.g. `git push origin docs-demo`. 

Keep in mind that you may need to update your docs-demo branch with ongoing changes that are made to the main jsPsych docs-demo branch. This is called [syncing a fork](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork). If you're tracking the main jsPsych repository with the name 'upstream', then you can run `git fetch upstream` to get the changes that have been made to the main jsPsych repo, and then `git merge upstream/docs-demo` to merge any changes made on the main docs-demo branch with your local docs-demo branch.

Once you're ready to submit your changes to the main jsPsych repo, go to the [Pull Request section of main jsPsych repo](https://github.com/jspsych/jsPsych/pulls) and [create a new pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request). At the top, click "Compare across forks". Then you can select the repositories and branches that you want to compare. For 'base' (the main jsPsych repo), you want to select the 'docs-demos' branch. For 'head repository', you want to select _your fork_ of the jsPsych repo (i.e. <your_name>/jsPsych). Then for 'compare', select the 'docs-demos' branch. Once you've done this, you should see all of your commits and file changes.

If you get a chance to work on this, please let us know what plugin you're working on, and whether you have any problems or questions. Thanks!!

**Comment by kurokida** [comment]
One thing I would like to confirm, should I use `var` to declare variables instead of `let` and `const`?

**Comment by becky-gilbert** [comment]
HI @kurokida, yes I think so, just to be consistent with the current docs and examples. I know always using `var` isn't considered best practice anymore, but we should probably change all of the docs/examples at once, at some point later on.

**Comment by kurokida** [comment]
Hi @becky-gilbert , thank you for your reply. I understood.
I've made a demo for canvas-button-response.
I will send a pull request from now. Could you confirm that I'm doing this right?

**Comment by becky-gilbert** [comment]
@kurokida Yes, absolutely! I'll look at your pull request and let you know. Thanks!!

**Comment by kurokida** [comment]
I have actually made a live demo of the canvas-button-response plugin, and noticed one thing.
It would be nice to be able to directly edit the code by visitor, and have it immediately reflected in the demo.
Is that too difficult?

**Comment by kurokida** [comment]
This is a continuation of my comment above.
Using [CodePen](https://codepen.io/), the users may be able to see changes in the code in real time. So my suggestion is to include CodePen in the documantation file if possible.

By the way, I am planning to create a live demo of jspsych-c***. I'll let you know here.

- canvas-button-response (already done)
- canvas-keyboard-response
- canvas-slider-response
- categorize-animation
- categorize-html
- categorize-image
- cloze

**Comment by becky-gilbert** [comment]
Great idea about using CodePen @kurokida. I'm not sure how hard it would be to incorporate CodePen demos into the docs pages,  but I'll look into it and update here. In the meantime I think we should carry on with the current plan. 

Thanks very much for letting everyone know that you'll be taking on the jspsych-c* plugin demos! I'll look out for the pull requests whenever they're ready 😃

**Comment by kurokida** [comment]
Hi, @becky-gilbert , thank you for your reply.

I tried CodePen. As a result, I found that it is very easy to embed in a document. See the attachment file.
![codepen-test](https://user-images.githubusercontent.com/32691644/124706346-0a5a9700-df32-11eb-974f-32c02b977fa4.png)

# The advantages and disadvantages are as follows

## Advantages

- Anyone can edit the source code, and the changes will be reflected in real time. 
- The color of the source code may be easier to understand
- We (maybe you and I) don't need to create files in the plugins/demos/ folder. All code is managed on CodePen.

## Disdvantages

- The documentation space is a bit small to display both the code and the experiment screen.
- We have to write code that is not directly related to the plugin (e.g., start, show_data, loop, and init) 

I would like to use CodePen to create documentations, but I don't think everyone else has to do it the same way I do.

Can I use CodePen to create the documentations?

I will gladly share how to use CodePen!

You can see [the documentation page I made using CodePen](https://github.com/kurokida/jsPsych/blame/CodePen/docs/plugins/jspsych-canvas-keyboard-response.md).

**Comment by SHogenboom** [comment]
Created a pull-request for the `jspsych-instructions` plugin: #1980

**Comment by becky-gilbert** [comment]
Thanks for putting this together @kurokida!

@jodeleeuw what do you think about Daiichiro's use of CodePen for the plugin docs examples/demos in the [comment above](https://github.com/jspsych/jsPsych/issues/164#issuecomment-875321377)? I think it looks great. It seems to me the biggest disadvantage is the last one mentioned above: having to include some code to make the demo run that isn't related to the plugin.

**Comment by becky-gilbert** [comment]
FYI for anyone else who might want to contribute to this - @SHogenboom has done the instructions plugin. So that means that the following plugins are already done or in progress:
- animation
- audio-button-response
- audio-keyboard-response
- audio-slider-response
- canvas-button-response
- canvas-keyboard-response
- canvas-slider-response
- categorize-animation
- categorize-html
- categorize-image
- cloze
- instructions

If anyone wants to take on a plugin that isn't listed above - please feel free! I'll update this list as any other plugin demos are finished or claimed.

**Comment by jodeleeuw** [comment]
Hey @kurokida and @becky-gilbert,

The code pen thing is pretty neat! I have a few concerns:

1. It looks like editable embedded code pens are only unlockable with a paid subscription to code pen. (https://blog.codepen.io/documentation/editable-embeds/). I think this removes one of the major advantages over the other system 😞.
2. I'm worried that the very narrow view for the preview will not be suitable for several plugins. I like that the current system gets twice the width for the demos.
3. There is something that I like about having the demos be part of the repository. We can better track changes to the demos and deploy changes when the docs are deployed. If the demos are in code pens that are owned by a variety of different contributors, then we may need to fork and relink those projects whenever the demos need to change. This feels less dependable to me.

I wonder if there is a way that we can get help users launch code pens without relying on it for the docs. For example, it looks like new code pens can be [created via an API](https://blog.codepen.io/documentation/prefill/), so in theory we could have links from the examples to open the example in code pen. I wouldn't want to do this if we have to manually script each link, but if there were a clever way to automate the link generation then that would be pretty sweet.

**Comment by becky-gilbert** [comment]
Thanks for the feedback Josh! Sounds like we should stick with the current demos, and look into automatically launching new Code Pens based on the demo code.

**Comment by kurokida** [comment]
Hi @jodeleeuw , thank you for your reply.

I agree with the current method of creating documentations without using CodePen. I strongly agree with the third point you are concerned about. I was completely unaware of this point.

But for the first point, maybe we don't need to be a paying member (PRO) to use editable embedded code.
On the page you introduced, it does indeed look like we need to pay.
But I could embed editable code without being a PRO member.
And, could you see the following figure which is a capture of the menu on the left side of the page you referred.

<img width="318" alt="スクリーンショット 2021-07-08 12 45 48" src="https://user-images.githubusercontent.com/32691644/124859274-916b4600-dfea-11eb-8899-420a19d81055.png">

You can see that only "PRO" is in front of "Unlimited Embed Themes".

Anyway, I will create documents according to the method @becky-gilbert explained to me. (Thanks @becky-gilbert !)
