### ISSUE TITLE
Inaccurate trial timing with webgazer extension

### ISSUE THREAD

**Issue by moltaire** [jspsych/jsPsych#1700]
I am not sure if this is a problem that jsPsych can solve, but I noticed that using the webgazer extension in its current form results in significant delays in trial timing.

For example running a sequence of 20 `html-keyboard-response` trials with simple text stimuli and `trial_duration = 500` with the webgazer-extension enabled gave me a mean trial duration of 653 ms, and a maximum error of 442 ms. Errors appear to get worse over time.
Disabling the extension gives maximum errors of 2 ms (even if the webgazer library is still loaded, and calibration and validation are run).

So, in its current form, the webgazer-extensions can't really be used for experiments sensitive to timing.

I'm not savvy enough with javascript to understand where the problem lies and fix this, but I'd be happy to help if there's something I can do.

**Comment by jodeleeuw** [comment]
Thanks for reporting this @moltaire. 

I tried replicating with a very simple example, and didn't observe terrible timing. My mean duration was maybe 520ms with a few ms on either side. Can you tell me a little more about the parameters of your test, including what browser/OS you are testing on?

**Comment by jodeleeuw** [comment]
I take it back. I was able to get poor timing with some small adjustments. It looks like the durations are getting somewhat longer as the experiment continues. I'm going to try and profile this and see what is causing the increase.

**Comment by moltaire** [comment]
I was hopeful for a moment after your first response.
Thank you for looking into this so quick!

I've compiled a "minimal" working example [here](https://github.com/moltaire/jspsych-webgazer-timing), which can be run under <https://moltaire.github.io/jspsych-webgazer-timing>, if that helps.
I've tested this on latest Firefox and Chrome on macOS.

**Comment by jodeleeuw** [comment]
I think I have a hacky solution for this. It involves some small changes to webgazer to decouple the gaze prediction from the `requestAnimationFrame` loop. Then jsPsych can manually get gaze predictions at some interval. 

I'm testing this a little more, and I'd be happy to share it with you. I'm not thrilled about this as a long-term fix since it requires forking webgazer. I may see if I can suggest some less hacky fix upstream to webgazer folks.

**Comment by becky-gilbert** [comment]
@jodeleeuw I'm curious about why the timing improves when you decouple the gaze prediction and rAF, and in particular if it is something I should be aware with rAF (rather than something specific to WebGazer or the WebGazer-jsPsych interaction).

**Comment by jodeleeuw** [comment]
@becky-gilbert I am curious about this too!

My best guess is that rAF blocks/has precedence over `setTimeout`, and when the code inside the rAF callback takes too long to run it is hogging the event loop. My alternative solution uses `setInterval` to periodically compute the gaze prediction on the most recent video frame. This might mean that moving `plugin.trial` inside a call to rAF is dangerous when there's a lot of computation inside `plugin.trial`. On the other hand, the code running in `plugin.trial` is different than webgazer code in one important way: we want the `plugin.trial` code to block progression if it is taking a long time to execute in most cases. But since webgazer is meant to sit on top and not interfere with the plugins we don't want to do that.

**Comment by moltaire** [comment]
Thank you for addressing this so quickly. It would have me taken much longer to find a fix that wouldn't be half as functional.
