### ISSUE TITLE
Release 6.3.1 still has 6.3.0 as the version number

### ISSUE THREAD

**Issue by amunn** [jspsych/jsPsych#1835]
The stored version number in `package.json`  is still 6.3.0 which makes checking for compatibility complicated.

**Comment by becky-gilbert** [comment]
You're absolutely right. Sorry about this, and thanks for flagging it. I just checked the jspsych.js file and can see that the `version` function is also returning 6.3.0. We'll update both package.json and the `version` function ASAP.

**Comment by becky-gilbert** [comment]
@amunn This should be fixed on the master branch now. There have only been a few commits to master since the v6.3.1 release on April 10th, and nothing that affects the experiment-related code (just documentation fixes and some new testing files - you can see the list of commits here: https://github.com/jspsych/jsPsych/commits/master). So if you want to have the current release with the correct version info in package.json and jspsych.js, you can download the master branch and use that as v6.3.1. And thanks again for flagging this - we'll be sure not to miss it in the next release!

FYI @jodeleeuw, I changed the jsPsych version number in the package.json version string and the jspsych.js version function - see dd9424c84dfd98ac9952df24768989ee949c4bc4. Just letting you know in case there's a problem with this that I'm not aware of, or if this also needs to be changed anywhere else.

**Comment by amunn** [comment]
Thanks @becky-gilbert. Since we're running on cognition.run for the moment we'll just have to ignore the difference unless they load the fixed version.

**Comment by becky-gilbert** [comment]
Oh no, sorry! You could try uploading the updated jspsych.js file in the External JS/CSS section, as that might overwrite the file that came with the 6.3.1 release, then try checking the version with [`jsPsych.version()` function](https://www.jspsych.org/core_library/jspsych-core/#jspsychversion). But if that doesn't work ,then I think you're right that you'll have to wait for them to load the fixed version.

**Comment by jodeleeuw** [comment]
I need to get in the habit of updating this with new releases 😬. 

We could hotfix the release to update the version number. I'm not sure what the most efficient way to do that is though, given that we've got other commits loaded onto the branch now.

**Comment by becky-gilbert** [comment]
@jodeleeuw yeah, we need some kind of reminder to do this for every release! 

There are a few other commits to master since the 6.3.1 release on April 10th but they're just documentation updates and the new testing folder: https://github.com/jspsych/jsPsych/commits/master So can we just replace the zip on the release page?
