### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by crfroehlich** [jspsych/jsPsych#195]
Orthogonal to #194, it would be great if JsPsych were available as an NPM package. If the plugins could have their own packages, all the better.

**Comment by jodeleeuw** [comment]
This is in the really early stages of development right now, but might happen in the next couple of months. Or sooner if someone else has the time to put into it.

**Comment by teonlamont** [comment]
@jodeleeuw I wouldn't mind making the npm package for you. it would help us out a lot.

**Comment by esolitos** [comment]
I guess this issue could be close considering it's available on NPM? 

https://www.npmjs.com/package/jspsych

**Comment by jodeleeuw** [comment]
It's an unofficial release that someone else made. We'll be overhauling the codebase to support ES6 modules and package management as part of 7.0.

**Comment by esolitos** [comment]
> It's an unofficial release that someone else made

I noticed that the GH links point to another repo, however following the links they actually redirect here, soi I was a little confused. :)

> [..] support ES6 modules and package management as part of 7.0.

That's great to hear! What's the progress on that? Because looking around I saw a linked thread which was very active in 2019, but now seems quiet and a closed pull request. :thinking:

**Comment by jodeleeuw** [comment]
Our current plan is a Q1 2021 release of 7.0. We've shifted attention to 6.2 issues recently, but once that ships we will be tackling 7.0 immediately.

**Comment by jodeleeuw** [comment]
This was completed with #2183
