### ISSUE TITLE
Interactive experiment with multiple objects on screen

### ISSUE THREAD

**Issue by matt-erhart** [jspsych/jsPsych#200]
Amazing work here by the way, looking forward to using it in an up coming pilot! I've done very little js, but a lot of programming (of experiments), so jspsych is great for my current situation. 

I'm going to be building an experiment that plays 9 different audio clips when subjects place the mouse in 9 different locations on screen: a 3x3 grid with a novel visual object in each cell. I'll need to trigger the sound by mouse x,y coordinates (doing eye tracking too), not by mouseover. Their task is to learn all the names of the novel objects. They will then go to a test screen with the objects in randomized order and will click on the object they hear. I plan to figure this out on my own, so no expectations here, but do you have any recommendations on how to best approach this in jspsych? Perhaps, a trial is created on each mouse over during a training screen? For the testing screen, they will need to make 9 clicks; what's the best way to store that kind of response? Happy to turn this into a plugin if I can get it working well. 

thanks,
Matt

**Comment by jodeleeuw** [comment]
For the training part, you're probably going to need a new plugin since the way that people are interacting with the trial is pretty unique. My recommendation would be to try coding that screen without jsPsych first. Once you get it working, it's easy to take the code you've generated and convert it to a jsPsych plugin. 

For the test trials, I'd recommend combining the single-audio plugin with the button-response plugin (currently on the /dev branch of the github repo; will be released in the next version). Use the single-audio plugin to play the sound, and then the button-response plugin to show the 9 objects and allow them to make a choice. You can use the `prompt` parameter of the single-audio plugin to display the objects while the sound is playing, but they won't be clickable until the button-response trial starts. Repeat the sequence 9 times for the different object names, treating each name as a new trial. The drawback of this approach is that they won't be able to click on the objects while the name is playing. If that's important for your design, you'll have to modify the button-response plugin to play audio.
