### ISSUE TITLE
visual-search-circle plugin: change required params for same vs different foils/distractors

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#2139]
I think there's a problem with the way this plugin works. The number of images to be displayed around the circle is based on `set_size`:
```js
var possible_display_locs = trial.set_size;
```
But there's no check to see whether the number of elements in the `foil` array is equal to `set_size` (or maybe `set_size - 1` if `target_present` is `true`?).

Currently, if `foil` isn't an array, then it's repeated up to `set_size`, otherwise the `foil` array is used as it is (with no check for the number of elements). The array of images to present is created by combining the `foil` array with the target (if it's present):
```js
var to_present = [];
if(trial.target_present){
  to_present.push(trial.target);
}
to_present = to_present.concat(trial.foil);
```
The images are displayed by looping over the length of `display_locs` (i.e. `set_size`), and indexing the foil/target image array:
```js
for (var i = 0; i < display_locs.length; i++) {
  paper.innerHTML += "<img src='"+to_present[i]+"' style='position: absolute; top:"+display_locs[i][0]+"px; left:"+display_locs[i][1]+"px; width:"+trial.target_size[0]+"px; height:"+trial.target_size[1]+"px;'></img>";
}
```
So there's no guarantee that the `to_present` image array will have the same number of elements as `display_locs`. I think this also means that you'd get different numbers of foils with the same `set_size` and `foil` array values, but with `target_present` being `true` vs `false`.  

So I think we should do the following:
- Change the implementation to check that either:
-- the number of elements in `foil` is equal to the `set_size` (or `foil.length +1`, if `target_present` is `true`?)
-- the number of elements in `foil` is 1, in which case this element should be repeated up to `set_size` (or `set_size - 1`, if `target_present` is `true`?)
- Produce a console warning or error if the above conditions aren't met.
- Decide whether `set_size` value should include the target, if it's present, or always just the number of foils. And clarify this in the docs.

**Comment by jodeleeuw** [comment]
Oof, I was sloppy with this!

I'm thinking a bit about the actual use cases here, and whether a small re-parameterization would be useful.

One use case is when you have a classic visual search experiment where the set size is varying and there is a single target and single foil. That's what I originally created the plugin for when I was doing an experiment along those lines. I think the current parameterization makes sense in this case (with `foil` being a `string` rather than an array).

A second use case would be to show a set of images, where one of the images might be the target. This is why the `foil` parameter was generalized at some point I suppose. I don't really recall the details of that. Here the problem is that the `target` `foil` distinction and the `set_size` parameters no longer really make sense. Ideally this would be specified as something like:

```js
var trial = {
	stimuli: ['1.png', '2.png', '3.png'],
	target_present: true, // just to get the correct vs. incorrect response in the data
}
```

It's making me think that the plugin should maybe be split in two, to handle the two different cases. If so, the first use case is, I think, way more common, and we should maybe simplify to that for now. Another option, which would be a little unusual given current design of other plugins, would be to allow for either `set_size`, `target`, and `foil` to be declared *or* for `stimuli` to be declared. If both are defined then we throw an error in the console.

What do you think @becky-gilbert ?

**Comment by becky-gilbert** [comment]
Sounds good to me! I'm not a vision person so appreciate the explanation 😃 

I think I'm in favor of the second option you mention: allowing both use cases in the same plugin, depending on the parameters that are provided. This does complicate things a bit and would need to be explained clearly in the docs. But there'd be a lot of repeated code if we split them into two plugins, plus the distinction between them is pretty subtle (both are visual search tasks with images in a circle, require a yes/no response re target, and store accuracy in the data). 

For the first use case, I'm still not clear on whether or not `set_size` should include the target (when present) - to me it makes sense that it would be included. If so, then `foil` would be repeated up to `set_size` when the target is absent, and up to `set_size - 1` when the target is present, i.e.
```js
// display 5 images: all foils
var trial_1 = {
  target_present: false,
  set_size: 5
}

// display 5 images: 4 foils and the target
var trial_2 = {
  target_present: true,
  set_size: 5
}
```

If I've understood correctly then I'm happy to make these changes for 7.0 and add them to this PR, if that works for you @jodeleeuw?

**Comment by jodeleeuw** [comment]
Yep, you've got it right! Yes, please go ahead and make those changes. Thanks!
