### ISSUE TITLE
Exp/Webgazer crashes after some time

### ISSUE THREAD

**Issue by Jonnyplate** [jspsych/jsPsych#2599]
Hi there,

we have a pretty long experimet with about 800 trials and somtimes the experiment crashes after a while. It only happens on slower PCs and mostly in the validation window: the fixation point freezes and console cant be opened anymore. Sometimes the console works again after a few minutes and we get this output:
Uncaught TypeError: Cannot read properties jspsych-webgazer-validate.js:270 of null (reading 'toFixed')
at validation_done (jspsych-webgazer-validate.js:270:76)
at next_validation_point (jspsych-webgazer-validate.js:95:9)
at watch_dot (jspsych-webgazer-validate.js:130:11)
so it seems that no gaze data was produced

Although the problem mostly occurs during validation, the exp sometimes also crashes during trials.
Has anyone come across this problem? I suspect that it might have something to do with memory, but am not sure. A workaround would be nice so that this error does not crash the whole experiment.
we are using jsPsych 6.3.1 for this experiment.

I anyone has an Idea I would be happy for help.

Thanks
Jonas

**Comment by bbonf** [comment]
Hello,

I experienced a similar issue with a longer experiment crashing (more often in Firefox, but on Chrome and Edge as well).
In my case the browser crashes completely, so I'm not sure this is the same issue, but it might be relevant.

It seems that there is a memory leak in the version of WebGazer that is provided by jsPsych. That leak is fixed in the latest version of WebGazer, but that won't work with jsPsych out-of-the-box.
I'm working on an adapted version over at https://github.com/UiL-OTS-labs/WebGazer which you could try to see if it solves your issue (but please don't rely on it being available and supported.)

More details about the memory leak:
I think it originates from the facemesh/face-landmarks model which is a dependency of WebGazer (and was last updated in https://github.com/brownhci/WebGazer/commit/96ecaa8b84a5d09ba4f0bcf5c4000a0bc3623f0a).
It's easy to see it in Chromium's dev tools: if you use the memory snapshots tool and filter for WebGLTexture, you should be able to see the amount of allocated textures increasing very quickly. With the newest version of WebGazer it remains constant as far as I can tell.

**Comment by Jonnyplate** [comment]
Hi bbonf,

thanks for your reply. That actually sounds promising. We have also noticed, that the facemesh in the camera init before the crashing calibration/validation phase is not shown anymore (I mean the dots that represent the face), so it could be the same Problem.
We will have a look at the WebGLTexture with the dev tools and I will let you know how it turned out.
Thanks for your help again!

**Comment by Jonnyplate** [comment]
It has been a while, but we have now solved the problem by changing the webgazer.js with your adapted version. Thanks again for your help!
