### ISSUE TITLE
How can I know which version did I use for my experiment?

### ISSUE THREAD

**Issue by idoba2030** [jspsych/jsPsych#2650]
Hey all,

I used jsPsych in my experiment 1.5 years ago and want to know now which version did I use. How can I find that information?

Thanks!

**Comment by bjoluc** [comment]
Hi @idoba2030,

your version should be something 6ish then, likely 6.2.0. For all versions prior to 7.0, you can use the [list of tags](https://github.com/jspsych/jsPsych/tags?after=v6.3-docs) to find the jsPsych version you downloaded based on the approximate time (or even exact time, if a timestamp of one of your downloaded files is still untouched). Since jsPsych v6.3, there is also a `jsPsych.version()` function that returns the version as a string. If you'd like to migrate to jsPsych 7, [here's how](https://www.jspsych.org/7.2/support/migration-v7/).

Cheers!
