### ISSUE TITLE
It's possible to call initJsPsych twice

### ISSUE THREAD

**Issue by alisdt** [jspsych/jsPsych#2684]
Just helping someone with their experiment, and the symptom was that jsPsych.data.get().values() returned an empty array, even after many trials had run.

In the end I found two calls to initJsPsych in the code. jsPsych.run() was called on one of these (inside a function) and the other was in a global var, so available in a conditional which was using jsPsych.data.get() -- but since it hadn't run any trials, jsPsych.data.get().values() was empty.

Anyway, if there's no clear use case for having more than one jsPsych object, maybe multiple instantiation should be prevented? (I'm by no means sure about this, just a suggestion!)

**Comment by jodeleeuw** [comment]
Thanks for raising this @alisdt. When we switched from the global jsPsych object in version 6 to the `initJsPsych()` approach in version 7 part of the motivation was to allow for more than one jsPsych instance. Admittedly the use cases are infrequent, but an example would be online documentation or a book where you want embedded, interactive examples with more than one per page.

I'm not sure if there are ways that we could warn users or make it easier to catch this kind of mistake. I'd be open to adding something, but it's hard for me to come up with a way to do this that would be able to distinguish between accidental and intentional uses of this.

**Comment by alisdt** [comment]
Understood, that seems reasonable. Maybe then it's something for the coding environment to catch -- makes me wonder if there's  a market for a jsPsych plugin for e.g. Atom or Visual Studio Code, I can think of a few other things it could do too ....

Anyway, thanks!

**Comment by jodeleeuw** [comment]
> Maybe then it's something for the coding environment to catch -- makes me wonder if there's a market for a jsPsych plugin for e.g. Atom or Visual Studio Code, I can think of a few other things it could do too ....

Sounds intriguing 🧐 !
