### ISSUE TITLE
The call_immediate parameter of jsPsych.timelineVariable() fails to work when callede explicitly

### ISSUE THREAD

**Issue by Shaobin-Jiang** [jspsych/jsPsych#2696]
In the documentation about `jsPsych.timelineVariable()`, it stated that:

> It is possible to explicitly set this option to `true` to force the function to immediately return the current value of the timeline variable.

Here, "this option" referred to the `call_immediate` parameter, which should mean that if I explicitly set it to `true`, the call to this method should return the value of the timeline variable instead of a function that will return it later.

However, when I tried it out using the code piece below:

```html
<!DOCTYPE html>
<html>

<head>
    <title>demo</title>
    <script src="https://unpkg.com/jspsych@7.2.3"></script>
    <script src="https://unpkg.com/@jspsych/plugin-html-keyboard-response@1.1.1"></script>
    <link href="https://unpkg.com/jspsych@7.2.3/css/jspsych.css" rel="stylesheet" type="text/css" />
</head>

<body></body>
<script>
    const jsPsych = initJsPsych();

    var procedure = {
        timeline: [
            {
                type: jsPsychHtmlKeyboardResponse,
                stimulus: `${jsPsych.timelineVariable('value', true)}`,
                trial_duration: 1000,
                choices: "NO_KEYS"
            }
        ],
        timeline_variables: [
            { value: 'value-1' }
        ]
    };

    jsPsych.run([procedure]);
</script>

</html>
```

An error was thrown: `Uncaught TypeError: Cannot read properties of undefined (reading 'timelineVariable')`.

I traced it back to the source code (the `jspsych.js` file in the release), and found that the method `jsPsych.timelineVariable()` is implemented thus:

```javascript
timelineVariable(varname, immediate = false) {
    if (this.internal.call_immediate || immediate === true) {
        return this.timeline.timelineVariable(varname);
    }
    else {
        return {
            timelineVariablePlaceholder: true,
            timelineVariableFunction: () => this.timeline.timelineVariable(varname),
        };
    }
}
```

However, if `immediate` is `true`, the call to `this.timeline` returns `undefined`, thus causing the error thrown in my provided example.

**Comment by jodeleeuw** [comment]
Hi @Shaobin-Jiang,

When you call the `timelineVariable()` function immediately in your code, there is no active timeline or timeline variables because the experiment is not running yet (`jsPsych.run()` hasn't been called yet). The declaration of the `procedure` variable happens prior to the experiment running, and so calling `timelineVariable()` when creating the variable results in the error that you've encountered. 

The `call_immediate` parameter should no longer be necessary to use in version 7+. If you call `jsPsych.timelineVariable()` in a context where there is no active timeline then it should return a placeholder function that will be invoked when the trial actually runs. If you call it in a context where there is an active timeline (e.g., inside [a function parameter](https://www.jspsych.org/7.2/overview/dynamic-parameters/)) then it should evaluate immediately.

**Comment by Shaobin-Jiang** [comment]
Understood!
