### ISSUE TITLE
fix duplicate body tags

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#316]
jsPsych adds a <body> to the DOM if one doesn't exist and the display_element is not set. But Chrome, and maybe other browsers, automatically adds a <body> when the document finishes loading. This causes duplicate <body> tags. Can we get Chrome to recognize that a <body> tag has been added via the script?

**Comment by jodeleeuw** [comment]
too much of a hassle with no clear solution. instead, just use a body tag!

**Comment by bjoluc** [comment]
Stumbled upon this one too. It also happens when `jsPsych.init()` is called from a script within the `head` tag, as the body is not set by then. The clear solution for all of these situations would be wrapping the internals of `core.init` into `window.onload = function () { ... }`. I validated that this works with a few of my projects, but the change fails 31 test suites which do not mimic browser behavior accordingly.

@jodeleeuw Are you still interested in working on this? I can offer my help in this case.

**Comment by bjoluc** [comment]
@jodeleeuw Are you willing to get this fixed? If so, I'm glad to do a PR.

**Comment by jodeleeuw** [comment]
Yes! Sorry I dropped the ball on this. Getting this into 6.2 would be great.

**Comment by becky-gilbert** [comment]
@bjoluc thanks very much for the fix, and sorry about the delay getting to this. You mentioned that you have some tests that cover this - do you have any written in Jest that could be added to jspsych/tests? If not then Josh or I can do it 👍

**Comment by bjoluc** [comment]
@becky-gilbert Thanks, I added two test cases for my change now (`init.test.js`)!
