### ISSUE TITLE
jsPsychSurveyMultiChoice behaves strangely with long preamble text

### ISSUE THREAD

**Issue by DominiqueMakowski** [jspsych/jsPsych#3171]
Not sure if that's a bug *per se*, but let's see. When I have a long preamble text in jsPsychSurveyMultiChoice it starts using 100% of the screen width (which just contrasts with most other plugins):

```js
var bdi2 = {
    type: jsPsychSurveyMultiChoice,
    preamble:
        "This questionnaire consists of 21 groups of statements. Please read each group of statements carefully. And then pick out the one statement in each group that best describes the way you have been feeling during the past two weeks, including today. If several statements in the group seem to apply equally well, circle the highest number for that group.",
    questions: [
        {
            prompt: "<b>1. Sadness</b>",
            options: [
                "I do not feel sad",
                "I feel sad much of the time",
                "I am sad all the time",
                "I am so sad or unhappy that I can't stand it",
            ],
            name: "bdi2_1",
        },
    ],
    data: {
        screen: "questionnaire_bdi2",
    },
}
```
![image](https://github.com/jspsych/jsPsych/assets/8875533/5f9c64fe-5fe9-42b6-94c0-ebb65b980148)

I tried to modify the preamble's style to center it, but unfortunately the items are still extreme left-aligned:

```js
var bdi2 = {
    type: jsPsychSurveyMultiChoice,
    preamble:
        "<p style='width:50%; margin-left: auto; margin-right: auto' align='center'>This questionnaire consists of 21 groups of statements. Please read each group of statements carefully. And then pick out the one statement in each group that best describes the way you have been feeling during the past two weeks, including today. If several statements in the group seem to apply equally well, circle the highest number for that group.</p>",
    questions: [
        {
            prompt: "<b>1. Sadness</b>",
            options: [
                "I do not feel sad",
                "I feel sad much of the time",
                "I am sad all the time",
                "I am so sad or unhappy that I can't stand it",
            ],
            name: "bdi2_1",
        },
    ],
    data: {
        screen: "questionnaire_bdi2",
    },
}
```
![image](https://github.com/jspsych/jsPsych/assets/8875533/6c04cdad-1e30-4df1-ac16-cf5c3fb6042d)

Any thoughts on how to fix / change that so that the elements remain a bit more centered? thanks!

**Comment by nikbpetrov** [comment]
Hard to tell much from your setup, but that's definitely weird. The `.jspsych-content` class sets the `max-width` to 95% so you should never actually have it to 100% width. The behaviour is consistent with this when I try to replicate it. Is it possible you're overwriting that class in your CSS?

**Comment by Shaobin-Jiang** [comment]
Short version : change `width: 50%` to `width: 50vw`.

This is not a bug actually. Given that `jspsych-content-wrapper` has `display: flex`, the child elements will only take up as much space as is necessary without exceeding `max-width`. In this way, the width of a parent element is to be decided by the child element. Let's take a look at the HTML structure now:

```html
<div id="jspsych-survey-multi-choice-preamble" class="jspsych-survey-multi-choice-preamble">
    <p style="width:50%; margin-left: auto; margin-right: auto" align="center">Your preamble</p>
</div>
```

Just a note, I am not myself very clear as to how the details work here, and what I am saying below is just my version of assumption.

So the `div` goes asking `p` how much space it needs, but it cannot possibly get an answer as the `width` of the child is set to `50%` so that it depends on the width of the parent. So `div` ignores `width: 50%` and has `p` stretch out to its full extent. As, in this way, `p` takes up the entire length of the screen (not the entire screen actually, as jsPsych as a 95% width limit, but you know what I mean), `div` obliges and also take up that amount of space.

With the width of `div` known, it can go back telling `p` how wide it can be: 50% of `div`. That is why your `p` is half as wide as `div` but `div` still takes up the entire width of the screen, forcing thereby the wrapper and correspondingly the question part below to be as wide.

With `width: 50vw` as I have suggested, however, when `div` goes asking `p` how much space it needs, it gets an exact answer and also takes up that amount of space, as `50vw` means 50% width of the viewport, which is a known value.
