### ISSUE TITLE
Show scroll bar for long surveys

### ISSUE THREAD

**Issue by DominiqueMakowski** [jspsych/jsPsych#3172]
My `jsPsychSurveyLikert` questionnaire has a few items that necessitate scrolling. I would like to show the scroll bar as sometimes participants can get confused.

Following [this](https://github.com/jspsych/jsPsych/issues/515), I tried for instance adding the CSS in my preamble:

```js
var pid5_questionaire = {
    type: jsPsychSurveyLikert,
    questions: questions,
    randomize_question_order: true,
    preamble:
        "<p style='overflow-y: scroll;'></p>" +
        "<p><b>About yourself...</b></p>" +
        "<p>Below is a list of things different people might say about themselves. Please select the response that best describes you.</p>",
    require_movement: false,
    slider_width: 700,
    data: {
        screen: "questionnaire",
    },
}
```

But it doesn't show the scrollbar. Any tips?

**Comment by nikbpetrov** [comment]
Not sure what the problem is here. This is not even replicable as you don't provide the `questions`. Are you trying to say that your questions' text is too long? These will get wrapped up and displayed as paragraphs so the scroll bar will eventually be on the entire page. Likewise, if you have too many options in the `labels` of your `questions`, these won't expand more than the width of the parent (set to 95% by default via `.jspsych-content`).

If you want to create a defined box for each question of, say, height 200px and add a scroll bar to that box, that's a different story, though not only is it difficult but also not very user-friendly in my opinion.
