### ISSUE TITLE
Use .key property for string-based key codes.

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#396]
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

**Comment by jodeleeuw** [comment]
@becky-gilbert I implemented this one in `feature-key-code-update`. It's a simple change, but there are a lot of affected locations in the code. They key point is that numeric keyCode values won't work anymore. Instead, it's all string-based codes. 

I tried to catch as many refs in the documentation, but I'm sure that I'm missing many places. If you can take a look for places that I missed that would be super helpful.

**Comment by becky-gilbert** [comment]
Will do!

**Comment by becky-gilbert** [comment]
Hey @jodeleeuw it looks like you have a bunch of webgazer-related commits on this [feature-key-code-update branch](https://github.com/jspsych/jsPsych/commits/feature-key-code-update). I was planning to check this branch and merge into master ASAP. Is that ok?

**Comment by jodeleeuw** [comment]
Ack, that was a mistake. I must have branched this from the webgazer branch by accident. I think it is safe to merge and when I push the webgazer stuff it will fix whatever problems this introduces. Unless there is a way to remove the webgazer stuff from this branch pre merge.

**Comment by becky-gilbert** [comment]
I thought that might've been the case 😃 Yep I think I can selectively remove the webgazer-related commtis with `git revert` without losing the later keyCode-related commits. If I can't get that to work then I'll just leave it and you can fix any merge conflicts etc.

**Comment by becky-gilbert** [comment]
Are we keeping all of the existing `pluginAPI` functions related to keys/keyCodes?
- `compareKeys`
- `convertKeyCharacterToKeyCode`
- `convertKeyCodeToKeyCharacter`

As far as I can tell, these won't be used in jspsych.js or any of the plugins in the next release. I guess they might be useful convenience functions for people to use when creating plugins, and for backwards compatibility?

**Comment by becky-gilbert** [comment]
And a related question - should we keep the existing `KEYCODE` parameter type?
```javascript
 module.parameterType = {
    BOOL: 0,
    STRING: 1,
    INT: 2,
    FLOAT: 3,
    FUNCTION: 4,
    KEYCODE: 5,
    SELECT: 6,
    HTML_STRING: 7,
    IMAGE: 8,
    AUDIO: 9,
    VIDEO: 10,
    OBJECT: 11,
    COMPLEX: 12
}
```
I think my vote is to change all of the key choice parameter types from KEYCODE to something like KEY or KEY_STRING in the `plugin.info` objects. I'm pretty sure all KEYCODE plugin parameters accept strings anyway, but changing the parameter type name would make it clearer that numeric key codes aren't allowed. 
So if we don't want to leave the KEYCODE type as-is, then one option is to replace the KEYCODE name with something else. Another option is to keep it for compatibility reasons, and add a new KEY/KEY_STRING type:
```javascript
 module.parameterType = {
    BOOL: 0,
    STRING: 1,
    INT: 2,
    FLOAT: 3,
    FUNCTION: 4,
    KEYCODE: 5,
    SELECT: 6,
    HTML_STRING: 7,
    IMAGE: 8,
    AUDIO: 9,
    VIDEO: 10,
    OBJECT: 11,
    COMPLEX: 12,
    KEY: 13
}
```

**Comment by becky-gilbert** [comment]
@jodeleeuw sorry, just to clarify: as part of this change you wanted plugins to stop accepting numeric key codes in their key parameters, right?

**Comment by jodeleeuw** [comment]
I think it's cleanest to drop support for the various keycode functions. If we want to maintain backwards compatibility, which is reasonable, then we could add a `console.warn` to these methods that suggests not using them anymore and that they may be removed in a future version?

I think replacing `KEYCODE` with `KEY` makes sense. There shouldn't be any compatibility issues to worry about because mostly these values are there for a future GUI if that project ever happens 😬.

And, yes, plugins should stop accepting numeric keycodes.

**Comment by becky-gilbert** [comment]
> I think it's cleanest to drop support for the various keycode functions. If we want to maintain backwards compatibility, which is reasonable, then we could add a `console.warn` to these methods that suggests not using them anymore and that they may be removed in a future version?

Good idea - much better than just removing these functions and hoping people catch it in the release notes! I'll take them out of the docs and leave them in jspsych.js with a `console.warn`.
 
> I think replacing `KEYCODE` with `KEY` makes sense. There shouldn't be any compatibility issues to worry about because mostly these values are there for a future GUI if that project ever happens 😬.

Yeah I was pretty sure the parameter types aren't actually used right now, apart from FUNCTION and COMPLEX. I just thought it'd be nice for the sake of clarity. (And in addition to being useful for a GUI, maybe at some point in the future, these parameter types could be used with some general-use parameter-value validation functions that run at the start of an experiment and flag any type errors)

> And, yes, plugins should stop accepting numeric keycodes.

Oh good. For a second there I thought maybe this was just supposed to apply to the data and that I'd have to undo a bunch of changes 😅

**Comment by becky-gilbert** [comment]
@jodeleeuw just found a bug with the way that we're handling the case sensitivity issue with the switch to `.key`. The problem occurs when the plugin does its own comparison between the key value that's passed from `jsPsych.pluginAPI.getKeyboardResponse` via the `callback_function`, and the key options that are specified in the trial parameters. When `case_sensitive` is `false` in `jsPsych.init`, the key press that's passed to the callback function will be the _lowercase version_, but this causes the plugin to break if that key is compared against a key choice parameter value that contains any uppercase letters.

For example, the instructions plugin uses "ArrowRight" and "ArrowLeft" keys as the default `key_forward` and `key_backward` choices. When `case_sensitive` is `false`, jsPsych's keyboard listener will convert the key response to lowercase, and return these keys as "arrowright" and "arrowleft". However, the instructions plugin won't respond to these keys because it does its own check against the `key_forward`/`key_backward` trial parameter values, and they don't match. 
https://github.com/jspsych/jsPsych/blob/599d1f5c72b1a27630cc0dd56772f8c7ddafee01/plugins/jspsych-instructions.js#L212-L220
We could convert the trial's key parameters to lowercase in the plugin file, but that would break the `case_sensitive: true` option.

The only way I can think of to solve this (while still fully supporting both case sensitivity options) is to use `jsPsych.initSettings` in the plugin file to determine whether `case_sensitivity` is `false`, and if so, convert trial's key parameter to lowercase before comparing it against the key that was returned from `jsPsych.pluginAPI.getKeyboardResponse`. The downsides of this are that (1) I'll have to go through all the plugins carefully to see if they do this sort of key/parameter comparison, and (2) it's kind of an annoying thing for people to deal with when they write their own plugins.

Any thoughts on this solution, or other suggestions?

**Comment by jodeleeuw** [comment]
Oof, that's unfortunate!

What about a pluginAPI function like compareKeys that checks init settings to see what to do, and we just recommend that plugin developers use that function whenever they want to compare two keys?

I think it should be different than compareKeys for the sake of backwards compatibility. Or at least if it changes compareKeys to do it in a way that doesn't break the old behavior.

**Comment by becky-gilbert** [comment]
Ah yes, good idea! How about `compareKeyStrings` or `compareKeyNames`?

 Or if you prefer to use `compareKeys` for this then yes, I can add this in without breaking the old behavior.

**Comment by jodeleeuw** [comment]
I think modifying the behavior of `compareKeys` is actually the cleanest solution.
