### ISSUE TITLE
Images/videos/gifs in documentation

### ISSUE THREAD

**Issue by ajhool** [jspsych/jsPsych#428]
I am considering adopting this library and believe it would be extraordinarily helpful to include more images/gifs/videos of the various tools in action (perhaps I'm just not finding them). Alternatively, a hosted Heroku demo would be beneficial, too. 

As I try out the various tools, I'll capture some screen grabs to add to documentation, but I would be surprised if these aren't already available somewhere and I just haven't found them

**Comment by jodeleeuw** [comment]
I agree that this would be helpful. Right now most of the examples live in the /examples folder in the GitHub repository. We're working on recording a few short GIFs to show some of the tools in action, but we don't have the resources right now to put a larger effort into this. 

We're working hard right now on a pretty big overhaul of the set of plugins in order to facilitate work on the new GUI, so now might not be the best time to put a lot of effort into recording the various plugins in action. By the end of next week the set of plugins should be stable again, and then help on this would be really appreciated.

**Comment by ajhool** [comment]
Ah, great, thanks! Please feel free to close this issue and I can reopen/PR
when the new set comes out
