### ISSUE TITLE
Issues with jspsych-form plugin #465

### ISSUE THREAD

**Issue by annguyen0212** [jspsych/jsPsych#466]
Running the jspsych-form example file gives me error. When I run it in Chrome I got Uncaught TypeError: Cannot read property 'insertAdjacentHTML' of null and running it in Firefox gives me TypeError: jsPsych.plugins[trial.type].info is undefined

**Comment by jodeleeuw** [comment]
@GavinQ1 If you have time to look at this that would be great. I suspect this is because the info method for the plugin isn't implemented, and some of the recent changes mean that the info method is mandatory.

**Comment by becky-gilbert** [comment]
FYI, I also get an error when running the jspsych-form.html example file in the new release (version 6): jspsych-text.js file not found. This error is fixed if I change the script source from jspsych-text.js to jspsych-html-keyboard-response.js. 
However I then get a loading error for the two stylesheet URLs, and "jspsych.js:832 Uncaught TypeError: Cannot read property 'parameters' of undefined" at jspsych.js 832.

**Comment by jodeleeuw** [comment]
The form plugin isn't intended to be supported in version 6 because there was still too many issues to sort through to get it working. I left the code in there (probably a mistake in hindsight), but removed references in the documentation. My goal is to get it working as part of the next minor update (6.1).

**Comment by jodeleeuw** [comment]
This plugin is not included in recent versions, so I'm closing this as out of date.
