### ISSUE TITLE
Keyboard listeners should be attached to window

### ISSUE THREAD

**Issue by fredcallaway** [jspsych/jsPsych#499]
Currently, getKeyboardResponses dosen't work before you click inside the target DOM element. I can't imagine why you would want this behavior—it was a real headache to debug it! I suggest attaching to `window`.

https://github.com/jspsych/jsPsych/blob/master/jspsych.js#L1839

**Comment by jodeleeuw** [comment]
This is intentional. There are use cases where jsPsych experiments are embedded inside DOM elements and we don't want mouse clicks or keyboard events that occur on elements outside the jsPsych experiment to be registered as being related to the experiment. 

I'm curious about your use case and what we could do to better support it. This generally isn't a problem when the experiment exists in the body element because it is usually the same size as the window.

**Comment by fredcallaway** [comment]
I’m using a ‘#jspsych-target’ element, which I believe was in the tutorial
when I started using JsPsych a couple years ago. I think using <body> would
make the most sense for a new user, so I’m probably just experiencing
growing pains :)

A quick note on this in the `init()` documentation would have saved me some
debugging time!


On February 7, 2018 at 1:16:26 PM, Josh de Leeuw (notifications@github.com)
wrote:

This is intentional. There are use cases where jsPsych experiments are
embedded inside DOM elements and we don't want mouse clicks or keyboard
events that occur on elements outside the jsPsych experiment to be
registered as being related to the experiment.

I'm curious about your use case and what we could do to better support it.
This generally isn't a problem when the experiment exists in the body
element because it is usually the same size as the window.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jspsych/jsPsych/issues/499#issuecomment-363913311>, or mute
the thread

**Comment by jodeleeuw** [comment]
Thanks for the suggestion to modify the documentation. I will definitely do that.

**Comment by jodeleeuw** [comment]
docs are now updated
