### ISSUE TITLE
html-slider-response not writing response or rt to trial data when timeout occurs

### ISSUE THREAD

**Issue by mkocsis2016** [jspsych/jsPsych#567]
When parsing data out of the JSON, would be handy when a timeout occurs on a html-slider-response trial that "response" = none and "rt "= -1 in trial data.

**Comment by jodeleeuw** [comment]
Can you explain why you prefer "none" and -1 as indicators instead of `null`, which is what is currently added to the data when the trial ends?

I think `null` is more semantically useful because -1 is numeric and can create issues when calculating values on the column using `jsPsych.data.get().select('rt').mean()` for example.

**Comment by mkocsis2016** [comment]
This may be a bug then because during testing an experiment I am finding that writing slider trial data at the end of a trial via:

jsPsych.init({
    timeline: timeline,
    'auto_preload': false,	
    on_data_update: function(data){
      if (data.hasOwnProperty('toWrite')){
        if (data.toWrite==true){
          subjRef.push(data);
            }
        }
     }
I am finding that when a no response is made, no 'response' or 'RT' value is being written to the database at all (see below):
![image](https://user-images.githubusercontent.com/21352570/46275600-1c909500-c590-11e8-8448-368ec43d7f02.png)

**Comment by jodeleeuw** [comment]
I added a test to verify that jsPsych is correctly sending null values to the `data` parameter in on_data_update. I wonder if something that you are doing downstream is affecting the presence of the null values?
