### ISSUE TITLE
Temporal Precision

### ISSUE THREAD

**Issue by FranzSkuffka** [jspsych/jsPsych#583]
jsPsych looks really interesting. I am curious about the precision of the framework.

Using a computer monitor introduces a maximum latency of roughly `15ms` with a refresh rate of `60Hz`.
Running experiments in a web browser which is by no means a platform geared towards presenting stimuli with a high temporal precision can introduce even more noise because frames are not rendered as quickly.

Do you have any data on how the temporal precision of jsPsych compares to e.g. PsychoPy, Presentation, Matlab?

**Comment by jodeleeuw** [comment]
The short answer is that the range of typical presentation errors is +/- 1 frame, and that the variability comes mostly from different browsers and operating systems.

The longer answer is...

Web browsers do a remarkably good job of rendering content quickly. Fast rendering is critical for common website features like smooth animations and smooth scrolling, and browser developers are very interested in this kind of performance. Given that most monitors have an upper limit in precision of ~16.67ms, all the browser needs to do is complete rendering in less than one frame to achieve precision that is comparable to desktop software. Most experiments are far simpler than a typical website, and rendering times of a single frame are often well under 5ms. 

The real limit on precision is not the speed of rendering but rather *scheduling* the rendering to take place at the right time. This is an area where standard lab software is a bit more reliable than online software, but the advantage is mainly because online software has to work on a variety of browsers and OSes, each of which behaves a bit differently.

We've been testing a variety of different algorithms for rendering content. You can see the latest analysis [here](https://vassar-cogscilab.github.io/js-display-durations/analysis/analysis.html). All approaches that we've tested have about the same error rates when you look across a variety of different operating systems and browsers, but some *should* be better than others because browsers do build in a tool for synchronization with the refresh cycle of a monitor. The problem is that different browsers implement this tool in different ways, so it has been challenging to find an algorithm with ideal performance on all machines. 

If you are running an experiment where the difference between having a stimulus on screen for 500ms vs. 517ms is a methodological deal breaker, then you should probably stay away from online software for now. Otherwise the precision shouldn't be a problem.

**Comment by FranzSkuffka** [comment]
Thanks for the elaborate response :)
