### ISSUE TITLE
preloading displays experiment fails to load when loading many items

### ISSUE THREAD

**Issue by neuronflow** [jspsych/jsPsych#605]
I preload 560 images around 10mb of data for my experiment...in addition to the buggy progress bar (#603 ) the loader displays Experiment failed to load in the background after around 60s. Though loading seems to go on correctly in the background and when it is finished the experiment is displayed correctly. I assume it is running into a timeout or something? Can I somehow increase the loading timeout before displaying this message?

When display of the progress bar is activated it also displays this error msg in the console after a while:
`132jspsych.js:2372 Uncaught TypeError: Cannot read property 'style' of null
    at update_loading_progress_bar (jspsych.js:2372)
    at Image.img.onload (jspsych.js:2284)`

See http://www.ibbmgroup.de/florian/mmg/

**Comment by meowlz** [comment]
was able to fix by increasing      ` 'max_load_time': 60000,`

Why is this set to only one minute? :)

**Comment by jodeleeuw** [comment]
I set the default at one minute because most experiments do load in under a minute, and the timeout is sometimes useful for diagnosing a server issue. But I think it's a reasonable point that maybe the default should be longer. 

I think ideally the pre-loading routines would be a little bit smarter. If the algorithm knows that there are 500 images to load and that progress is steady, then there's no reason to time out. I'd be very open to improvements along this line.

We do need to fix the behavior that the experiment continues to load after this time out message, so I'm leaving this issue open as documentation of that problem (and maybe as a nudge to change the default).

**Comment by jodeleeuw** [comment]
This is obsolete with the shift of preloading behavior to the preload plugin.
