### ISSUE TITLE
safari: survey-text submit causes page to refresh

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#610]
This is fixed by adding `onsubmit="return false;"` but I don't know if this has other consequences that need to be considered.

**Comment by nabsul** [comment]
I was able to reproduce this bug on Edge as well. Doesn't happen in Chrome.

**Comment by nabsul** [comment]
The correct way to fix this is to add a call to event.preventDefault() in the submit function of `survey-text`. 

I checked out other trials such as `survey-multi-choice` and they already have this in their code, so I think it was just missed by mistake.

@jodeleeuw It looks like they'll have this fixed in 6.0.6, but you can make the fix yourself as show in the pull request that I've submitted.

**Comment by jodeleeuw** [comment]
fixed in #613
