### ISSUE TITLE
Make jsPsych runnable in Node/modular

### ISSUE THREAD

**Issue by ryandrew14** [jspsych/jsPsych#625]
Hi! I'm Ryan, a student at Northeastern University. I'm part of a student organization, called [Sandbox](https://sandboxneu.com), that builds open-source software for researchers. This year, I led a team that built a [psychology application](https://github.com/sandboxneu/predictive-affect) with jsPsych. We loved the library and it enabled us to replicate what had previously been done in PsychoPy in a web-deployable manner.

Recently, I refactored our experiment a bit to use modern JS features like modules to organize the repository better and add unit tests with Mocha. One thing I noticed is that jsPsych did not play very nice with Node, as it's optimized for the browser so NodeJS support really means next to nothing for the library. However, I did a little tinkering in the repository and managed to come up with a [band-aid solution](https://github.com/sandboxneu/jsPsych) to get the tests running.

I'm wondering if this is something you've thought about, or something that you'd like work done on. If so, I'd love to work with you to develop some acceptance criteria for something like this. Here's a non-exhaustive list of things I'm thinking about:
- `const jsPsych = require('jspsych')` or `import jsPsych from 'jspsych'` -- getting the jsPsych object from an import statement rather than relying on `window` (which does not exist in Node)
- plugins can also be imported, possibly configured in a `jsPsych.config.js` similar to [Gatsby's config file](https://www.gatsbyjs.org/docs/gatsby-config/)
- possibly adding an NPM package for each plugin (think `@jspsych/html-keyboard-plugin`) instead of including them by default, mostly to decrease the bundle size and make configuration easier

**Comment by jodeleeuw** [comment]
Hi @ryandrew14 !

Short answer: YES. 

This is something we have been thinking about (#529, #556, #195 ) but I haven't had the time to properly pull it off. If you are willing to take the lead that would be a **huge** help to making this happen. 

My main sticking point is that I don't want the setup to get more difficult for people who are not using node or npm. Learning either of those is an additional barrier to entry. So if you have ideas about how we can keep the base experience the same and transition to proper modules I'm eager to hear them.

**Comment by jodeleeuw** [comment]
PS - Sandbox looks like a great organization. Very neat!

**Comment by ryandrew14** [comment]
Thanks for the feedback @jodeleeuw ! Sorry for duplicating this issue -- I think I searched "node" in the issues and for some reason didn't find anything. That sounds like something I'd be interested in for sure. My teammate at Sandbox, @sarah-witt, will also be around to help out. My current solution actually does maintain the old experience, but there are a few other things I need to fix so that the plugin experience is the same for potential plugin developers.

I have a bunch of ideas for this. Let me gather them together and propose something more complete. Will you be actively working on jsPsych during the summer?

**Comment by jodeleeuw** [comment]
Yes, I'm actively (but intermittently) working on jsPsych over the summer. I'd be happy to review a proposal for how to make the transition. Thanks a bunch for working on this!

**Comment by ryandrew14** [comment]
Awesome. Should I just post that here when I have it ready?

**Comment by jodeleeuw** [comment]
Yeah, that'd be great!

**Comment by jdpigeon** [comment]
Hey guys,

This is really relevant to my interests as well. The current shakiness we're dealing with in the [jspsych-react](https://github.com/makebrainwaves/jspsych-react) are related to poor modularization of the jspsych code.

We're working on a branch of jsPsych that's compatibly with ES modules and CJS here: https://github.com/makebrainwaves/jsPsych/tree/modular. This branch was working for us with very particular babel and webpack versions, but I think I may have broken it upon merging in the latest commits to bring it up to speed with the main jsPsych repo. Hopefully it helps!

**Comment by ryandrew14** [comment]
Thanks @jdpigeon! It looks great, and the changes are similar to what I have (yours are far more robust). I have a question -- why did you call the argument `factory` in the plugin files? Is this a standard modularization convention?

**Comment by jdpigeon** [comment]
Hey @ryandrew14. Sounds good! Maybe in August we could work on merging these modularization changes into the main jsPsych project.

As for your question, I am still learning this myself, but it seems that, for the most part, we're following the UMD convention as defined here: https://github.com/umdjs/umd/blob/master/templates/returnExports.js and the `factory` parameter is a standard part of that.

**Comment by ryandrew14** [comment]
Hey @jodeleeuw -- Circling back on this now. Wondering if we can get a `feature/modularization` branch going here so @jdpigeon and I can merge our changes in and work off of the same branch

**Comment by jodeleeuw** [comment]
Great idea. All set:

https://github.com/jspsych/jsPsych/tree/feature/modularization

**Comment by jodeleeuw** [comment]
@ryandrew14, @jdpigeon: you now have write access to everything but the `master` branch.

**Comment by jodeleeuw** [comment]
I'm also wondering if the right strategy for modularization is to adopt ES6 modules, given the ]widespread support](https://caniuse.com/#feat=es6-module) for `<script type="module">`. It's certainly a cleaner syntax than UMD.

**Comment by ryandrew14** [comment]
I totally agree -- seems way better to use that over UMD/AMD. I think we will need to add Babel if we're going to use ES6 -- apparently all ES6 modules currently get compiled down to CommonJS modules (`module.exports = {}` and `require()`) by Babel anyways.

There's no IE11 support for `<script type="module">` which scares me a little... what do you think about keeping the existing API, but also adding module support?

We could also do something similar to React and provide a create-jspsych-experiment command that will set up a basic jsPsych directory with Webpack so that they don't have to worry about the build. This would be a lot of work though.

**Comment by ryandrew14** [comment]
Also, wanted to ask what you think of having `jspsych.config.js`. This would be to have an easy way to specify plugins, my proposal is that it would have one export like this:
```
module.exports = {
  "plugins": [
    "@jspsych/double-slider-plugin",
    "@jspsych/html-response-plugin",
  ]
}
```

The other thing to figure out is if all the plugins should be included in the main package, or if they should be separate packages under the `@jspsych` NPM namespace. Do you have thoughts here @jodeleeuw ?

**Comment by jodeleeuw** [comment]
Thanks for all these excellent thoughts. A few of my own:

1. I'm not really concerned about maintaining compatibility for IE at this point. There are probably other aspects of the library that are already not compatible.
2. I'm out of my expertise: Do we need Babel if we are relying on native modules? I thought the idea was that native modules can be ready with no compilation. Is the concern about support for browsers that don't support native modules? If so, I think we can (temporarily) release with some kind of polyfill. I've seen a couple floating around in articles about native module support.
3. I *really* feel strongly about avoiding any kind of requirement that users need to run any kind of build script. I think this would be a significant barrier for the users for whom jsPsych is their first significant experience with programming. I see the purpose of this refactoring as offering better support for experienced users who want to integrate with other frameworks that require modules.
4. Thinking along those lines: What's the benefit of `jspsych.config.js` for new users? Relying on `<script>` tags means one less thing to learn when you are getting started.
5. It is probably best if plugins live in their own packages. That'll make it a lot easier for the plugin ecosystem to grow. The trick is to figure out a way to do this that doesn't rely on new users installing npm. Maybe two distributions are released: stand-alone jsPsych and jsPsych with a default set of plugins.

**Comment by jdpigeon** [comment]
Excited to see movement here! We've started using jsPsych internally and making the switch to modules will make my job easier.

I'm intrigued by the native ES modules thing. From what I understand from this article: https://salomvary.com/es6-modules-in-browsers.html, one of the biggest limitations of native modules is the ability to import external dependencies. However, because jsPsych doesn't have any dependencies, it may be a good candidate!

That said, my experience with jspsych-react using the UMD export definition has been pretty successful. After my last update I haven't heard of any import-related issues.

**Comment by bjoluc** [comment]
@ryandrew14 I built a little jsPsych development setup [here](https://github.com/bjoluc/jspsych-builder) recently that uses gulp, webpack and babel (and also packages the resulting experiment, even for JATOS). Is this something comparable to the results of a create-jspsych-experiment tool that you proposed earlier?

@jodeleeuw
* regarding 4. I agree that jsPsych should be as easy to use as possible for beginners. Ideally, we would still offer a way for <script> imports but provide more advanced users with a beautiful setup.
* regarding 5. It would be quite nice to have a CD pipeline build a packaged version of jsPsych that beginners can download. One could also use babel during the build and thus ensure that inexperienced users do not have to worry about browser compatibility or run some sort of create-jspsych-experiment tool.

**Comment by jodeleeuw** [comment]
@bjoluc: One concern I have about a build pipeline is that makes it harder for beginners to tinker with plugins. If a plugin file needs to run through a build script then plugins aren't as easily modifiable for new users as they are currently. Maybe there is some kind of solution for this, but I'd want to be convinced that the experience for people who have never done any web development is not any harder than it currently is. Ideally it would be easier!

**Comment by bjoluc** [comment]
@jodeleeuw: Absolutely right. I didn't think about that. Too bad. If we do not use any transpilation (which, according to http://kangax.github.io/compat-table/es6/, does not even seem too unrealistic), a pipeline could still be a nice way to package a default set of plugins.

**Comment by ryandrew14** [comment]
There are a lot of interesting thoughts here. I think when I originally thought about this, I thought about it in the context of a traditional modern JS library and tried to fit jsPsych into that box. Now that you say all these things @jodeleeuw I totally get where you're coming from and I might have to rethink how I was reasoning about the transition -- the modern features make it much harder for beginners to use it.

The two use cases I want to solve:
- Writing jsPsych code in ES6 modules
- Testing jsPsych code in NodeJS

Solving these doesn't mean necessarily totally modularizing everything. Let me take a few days to think over this and see if I can come up with something that involves minimal changes but will allow these use cases.

One more thing we could potentially do is export the standard jsPsych library and then make a separate NPM package `modular-jspsych` or something that's not for beginners and is then totally modernized in ways many people are suggesting. This would basically be a wrapper around the default library... not sure if this is possible but it would be awesome if it is. Maybe the nonmodular one should be a wrapper around the modular one?

**Comment by jodeleeuw** [comment]
Do you mean some kind of testing that is different than the test suite that's already implemented in the [/tests folder](https://github.com/jspsych/jsPsych/tree/master/tests)?

**Comment by ryandrew14** [comment]
Oh sorry, I worded that weirdly -- I meant users testing their code, not the code itself being tested. It's doable but not intuitive to have to require the jspsych file with code like this:
```javascript
beforeEach(function(){
  require(root + 'jspsych.js');
  require(root + 'plugins/jspsych-html-keyboard-response.js');
});
```

In a similar vein, I meant users writing ES6 modularized code with jsPsych calls in it, not jsPsych itself being rewritten in ES6 modules.

**Comment by jodeleeuw** [comment]
Got it, that makes sense. 

I do think that adopting ES6 modules as the default solve all these problems. I don't see ES6 modules as any more difficult to use than the current plugin system. There's no need to install `npm` or run build scripts if you are using `<script type="module">`. The only significant downside is officially dropping any hope of supporting IE. [Current usage stats](https://caniuse.com/#search=module) put adoption in the high 80% range, and that should only go up. There's probably [a way to polyfill](https://github.com/ModuleLoader/es-module-loader) that could be shipped by default, or pointed to as an option.

**Comment by nx10** [comment]
Is there any update on this? 

The branch does not seem to be active

https://github.com/jspsych/jsPsych/tree/feature/modularization

**Comment by jkhartshorne** [comment]
@hrcn and I are taking up the problem of using native modules. We found that turning jspsych into a native module works smoothly and doesn't break backwards compatibility. We're now thinking about how to handle plugins. 

Are @ryandrew14 or @jdpigeon or @bjoluc still interested in working on this issue?

**Comment by ryandrew14** [comment]
I'm happy to work on ES6 conversion with you -- I was just previously a little daunted by taking the task on alone in the middle of the semester which is why I went quiet 😬 next time I will say something instead of ghosting.

Let me know what your plan for moving forward is. I'm especially interested to hear your thoughts on plugins.

**Comment by jkhartshorne** [comment]
@ryandrew14 Please check out https://github.com/hrcn/pushkin-jspsych!

**Comment by bjoluc** [comment]
Hi all, I'm stunned how fast the time has passed! Meanwhile, I created [jsPsych Builder](https://github.com/bjoluc/jspsych-builder) to provide an easy-to-use babel/webpack setup (and some other goodies) for jsPsych, similar to what @ryandrew14 [mentioned](https://github.com/jspsych/jsPsych/issues/625#issuecomment-521878887).

I am in the lucky position of having some capacities for ES6 modularization now, and I'd like to boost this a bit – also considering the upcoming v7 release. Here are my thoughts:

*  By decomposing jsPsych itself, we can provide the best ES6 module support possible. I think the v7 release is a great chance to finally make use of ES6 features (and probably also external NPM dependencies) in core jsPsych.
* [Rollup](https://rollupjs.org/guide/en/) is a popular way (amongst many other options) to do the transition to ES6 right away and still keep supporting old browsers, i.e. shipping a bundled version (specifically in the iife format). I'd really like to use such an approach and stop worrying about browser compatibility in the core jsPsych code. Advanced users can use the ES6 version of jsPsych then, and anyone else can still include it traditionally. @jodeleeuw has a point with the ["tinkering with plugins" consideration](https://github.com/jspsych/jsPsych/issues/625#issuecomment-523567256). This certainly is a tradeoff, but one jsPsych will have to face, IMHO. The JS ecosystem has evolved rapidly since when jsPsych was born and transpilers and bundlers are now an important part of it. For the neat features and enhanced developer experience that modern JS offers us, this is the price we'll have to pay, sooner or later. Rather than trying to hide the build tools from beginners, I'd like to make them as easy to use as possible. Because beginners do also profit from modern JS, and it is getting increasingly harder to learn widely compatible "oldschool" JS nowadays. Beginners must constantly be facing modern JS features on StackOverflow, and trying to avoid them for the sake of browser compatibility is something that I wouldn't even want to do as an advanced JS user.
* Plugins: I like the suggestion to publish plugins as individual packages in a `@jspsych` NPM namespace. This would work nicely with [this](https://github.com/jspsych/jsPsych/issues/529#issuecomment-416354303) approach from #529. What about maintaining them in a monorepo and having a script build them before publishing (and in a development/watch mode to allow traditional tinkering)? Traditional users could include plugins via a CDN (such as [unpkg](https://unpkg.com/)), without even downloading them. Modern (ES6) users could `npm install` them and `import` them so they included in their bundles.

These are some pretty heavy suggestions of mine. But I think that jsPsych would largely benefit from them on the long term. I could set up the tooling as a starting point.
What are your thoughts on this matter, @jodeleeuw @becky-gilbert @ryandrew14 @jdpigeon @jkhartshorne?

**Comment by jodeleeuw** [comment]
Thanks for the really thoughtful ideas @bjoluc !

Let me preface this next part by saying that I don't feel like I have a lot of expertise in modern JS tooling. I've built a few react apps and such, but I've never set up tooling from the ground up. So maybe some of my concerns are unfounded if I understood things a bit better.

Here's the scenario that I'm concerned about with the transition to requiring a build chain:

With the current jsPsych (lack of tooling): A psychology student with no web development experience and a little bit of programming experience decides to use jsPsych to create an experiment. The student follows the tutorials, and encounters a relatively familiar pattern of operations for a non-programmer. Some stuff needs to be downloaded, put into folders, and a file or two need to be created. Opening the file launches the experiment once the code is set up. Changes can be made directly to the file and immediately the consequences are apparent. Eventually, the student might discover the need to modify plugin files, and this has the same familiar feel to it, albeit with a little more JS/HMTL/CSS knowledge needed.

With a modularized jsPsych: The same student wants to set up the experiment, but is now confronted with installing `npm` and figuring out what that's for. Opening files directly isn't possible anymore, so the student has to learn about hosting a local webserver. When changes to a plugin file need to be made, the student now needs to understand the build chain enough to be able to run it, and may be put off by not understanding all the things that are going on, making it conceptually harder to understand how to debug. 

I realize that learning all of this stuff *in the long run* is good, but I think it's important that jsPsych remain a tool that is friendly to new programmers with as few barriers as possible.

My hope would be that something like Rollup could allow us to have both experiences available. If we can produce non-minified .js files for the plugins that have relatively little wrapping around them, then it seems like a new user could just edit those files directly and bypass the entire build chain. But my (very limited) experience with bundlers is that they often make the code less legible on the output side.

I'm hoping to get the 7.0 work more seriously underway next week and this will be the first major decision point to tackle. Happy to be educated about cool modern JS tools that I know little about!

**Comment by bjoluc** [comment]
Thanks for the open-minded reply @jodeleeuw!
> With a modularized jsPsych: The same student wants to set up the experiment, but is now confronted with installing npm and figuring out what that's for.

Let me argue that, using unpkg, there is no need to install Node.js for that student unless they want to modify existing plugins. The student doesn't even have to download the jsPsych repo – a simple experiment can be a standalone HTML file.
If the student wants to modify plugins, however, installing Node.js is fairly simple at least. Here's how I would reason it:

"There are different versions of the JavaScript language specification and not all web browsers and browser versions support all new JavaScript features. That's why jsPsych uses a build chain to translate the source files into code that a majority of web browsers can understand. To execute the build chain, you need to have Node.js (link) installed, a runtime to execute JavaScript code without a web browser. Node.js comes with a package manager called NPM (Node Package Manager) that can install JavaScript libraries to run on your machine, such as the build tools for jsPsych." Then there would need to be a list of steps, namely: Clone the repo, run `npm install`, and in the directory that contains the plugin, run `npm run watch`.

> Opening files directly isn't possible anymore, so the student has to learn about hosting a local webserver.

Luckily not! The build chain can output plain JS files that can be included just like before. The only change here is the "transpilation" step between writing the code and handing it out to the browser. Tools like create-react-app and jspsych-builder (both webpack under the hood) only offer the local dev server for convenience, i.e. features like hot reloading so one does not have to refresh the page after every source change.

> When changes to a plugin file need to be made, the student now needs to understand the build chain enough to be able to run it, and may be put off by not understanding all the things that are going on, making it conceptually harder to understand how to debug.

Well, running the build chain is just running "npm run build" or "npm run watch" or so. Basically, all one needs to know is the reasoning behind the build chain, and hence what it does (e.g., as described above). Regarding debugging: A good build chain should just get out of the way and ideally never needs to be debugged, at least not by the user. When it comes to debugging jsPsych or user code, for instance in a web browser, I suggest we let the build chain generate source maps. Browsers automatically show the original source code in their debugger then instead of the transpiled one.

> I realize that learning all of this stuff in the long run is good, but I think it's important that jsPsych remain a tool that is friendly to new programmers with as few barriers as possible.

I totally agree with that. Luckily, for simple use cases, i.e. without writing plugins, the modular approach could even simplify the setup (using unpkg). For custom plugins or tinkering with existing ones, the setup would get slightly more complex. But it would also vastly decrease the number of "it does not run on browser X, version Y" problems, which is worth the extra step, I think.

> My hope would be that something like Rollup could allow us to have both experiences available. If we can produce non-minified .js files for the plugins that have relatively little wrapping around them, then it seems like a new user could just edit those files directly and bypass the entire build chain. But my (very limited) experience with bundlers is that they often make the code less legible on the output side.

Rollup certainly can. The iife output really just looks like a manually written function, even the indentation is correct. However, I strongly suggest that we take the chance and include Babel in the build chain to tackle browser compatibility. It is one of the sweetest tools in the world :smile: Depending on the [browsers we target](https://babeljs.io/docs/en/babel-preset-env#browserslist-integration), Babel may or may not "pollute" (I'd say enrich ;)) the output with polyfills, making it harder to read and work on. The last step to finally destroy any hope to read a piece of code are Terser and friends – which I suggest we use for the unpkg distribution since source maps are available anyway. So yes, we may be able to offer "both experiences", but we would loose most of the benefits of a build chain then.

I took the time and did most of the heavy lifting [here](https://github.com/bjoluc/jsPsych/tree/modularization). Some tests do not pass yet due to some mocking oddities that I hope do go away when jsPsych itself has also been decomposed into multiple modules. To try out the new setup, make sure you have npm v7 installed (for the workspaces feature; included natively in Node 16, otherwise available via `npm i npm@7`), run `npm install` in the repo root (which will already build everything) and try out the [timing-tests](https://github.com/bjoluc/jsPsych/tree/modularization/packages/jspsych/tests/timing-tests) example (I didn't yet update the examples in `/examples`).
Running `npm run watch` in a package directory (core or plugin) will start Rollup in watch mode so that it updates the dist files when the source files are modified. If you think this setup is something we can tweak and build upon, I'm happy to open a PR so we can work on it together!

**Comment by jodeleeuw** [comment]
Thanks for all of this @bjoluc. I'm learning a ton.

I've still got some hesitancies about particular trade offs. Do you think we could set up a chat at some point? I feel like a real-time conversation would be useful. Feel free to email me (jdeleeuw@vassar.edu) if you are interested and we can schedule something. Maybe @becky-gilbert can join too.

**Comment by becky-gilbert** [comment]
Yes please keep me in the loop (beckyannegilbert@gmail.com)! In general I have the same hesitancies that Josh mentioned and would like to be sure that things remain as easy as possible for novice/intermediate programmers with no prior web development experience. I also find myself frequently recommending minor tweaks to the plugin code in response to Discussion board questions, so I'd like to make sure I understand how plugin modifications will be affected.

**Comment by jodeleeuw** [comment]
This was completed with #2183
