### ISSUE TITLE
Problem outputting nested stringified data to JSON.

### ISSUE THREAD

**Issue by stefanuddenberg** [jspsych/jsPsych#670]
In the current implementation of jsPsych, there is a problem handling trials with complex nested data. This is most easily illustrated in the `jspsych-instructions` plugin via the `view_history` property in `trial_data`. 

The current solution implemented is to stringify the `view_history` array using `{ view_history: JSON.stringify(view_history)... }`, which allows for sensible conversion to CSV. Without stringifying `view_history`, those `view_history` data would show up in the CSV as `[object Object]`. However, if you attempt to get the JSON data for the experiment, it cannot later be parsed with `JSON.parse` (or the json library in Python) due to problems resulting from attempting to parse a stringified JSON object within a stringified JSON object. 

My current solution is to use the `parse` function from the `json2csv` library (available on npm) to replace the `JSON2CSV` helper function in `jspsych.js`. This allows me to have both sensible CSV and JSON representations of the data.

**Comment by jodeleeuw** [comment]
Thanks for raising this issue @stefanuddenberg. I'm guessing the solution here is to update the JSON2CSV helper that we currently have, and I'll add that to the list for the next minor release.

This also connects with issues about what format the data should be stored in within jsPsych's data structure. I've been operating under the idea that the data for each trial should only be primitive types, and that arrays and objects should be stored in their JSON-encoded format. This might be overly restrictive.

**Comment by jodeleeuw** [comment]
Revisiting this as we work towards shipping 6.2.

@stefanuddenberg I'm trying to better understand your solution. Is the idea that you replace the CSV conversion function *and* change the plugins so the data is stored as nested objects instead of a string?

Does: 

https://github.com/jspsych/jsPsych/blob/a2b0cecfbb67e2fc0dc896329913c8f0c8f65b86/plugins/jspsych-instructions.js#L194

become 

```js
view_history: view_history
```
?

**Comment by jodeleeuw** [comment]
I'm going to bump this to 7.0 because it'll involve a bigger overhaul to the data storage mechanisms.

**Comment by stefanuddenberg** [comment]
Sorry for not seeing this sooner; Github does not do a good job of notifying me about activity on posts it would seem! That's precisely the approach that I took in my own fork of the project; I'm using the [json2csv](https://www.npmjs.com/package/json2csv) library to handle the csv-ification of the jsPsych data.

**Comment by jodeleeuw** [comment]
@becky-gilbert I went ahead and worked on this in the `feature-objects-arrays-in-data` branch. 

It changes a core design idea: now we store objects and arrays in the data directly, instead of JSON versions of them. I updated all of the plugins that this affects, wrote a simple test to check the output of both `.json()` and `.csv()` methods in `jsPsych.data`, and updated the CSV conversion function.

Things that should probably happen before a merge:

- [ ] Add tests to the new test files for a few other plugins that generate arrays/objects in the data.
- [ ] Check the `examples` folder to see if any of the examples use `JSON.parse()` on data objects that are now not JSON.
- [ ] Check the docs to see what needs to be updated to reflect this change.
