### ISSUE TITLE
Documentation type mismatch for *-button-response-plugins

### ISSUE THREAD

**Issue by vijaymarupudi** [jspsych/jsPsych#682]
In the code, this value is always going to be a string <https://github.com/jspsych/jsPsych/blob/9de501e9da37ca2329e842344bff8cca7c02e00e/plugins/jspsych-html-button-response.js#L132>

However in the documentation, the type is numeric. <https://github.com/jspsych/jsPsych/blob/master/docs/plugins/jspsych-html-button-response.md>

This would be a breaking change, but I would follow the documentation, and parseInt the choice in the next release of jsPsych!

**Comment by jodeleeuw** [comment]
Thanks for flagging this issue @vijaygopal1234 !

**Comment by becky-gilbert** [comment]
I just modified the *-button-response plugins so that they save the "button_pressed" data as an integer rather than a string, which is consistent with the docs. All tests still pass. Closing this issue now. 
@jodeleeuw let me know if you wanted to keep the "button_pressed" values as strings and change the docs instead, in which case I'll reopen and make those changes.

**Comment by jodeleeuw** [comment]
This is great, thanks!
