### ISSUE TITLE
Plugin for visual analog scale surveys

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#734]
Like the `*-slider-response` scales, but for multi-item surveys.

Also raises a possibly interesting abstraction that could be made. Could chunk various common elements (like visual analog scales) into the `pluginAPI` portion of the library and wrap them in `createVisualAnalogScale()` etc. functions. Might make constructing new plugins easier.

**Comment by becky-gilbert** [comment]
@jodeleeuw is this pull request #1306 what you had in mind for this issue? (Also discussed here: #1147). Although this PR doesn't address the abstraction issue: moving certain things that are currently repeated across plugins into the pluginAPI.

I'm wondering whether #1306 should be linked to this issue so that merging it will close the issue. What do you think?

**Comment by jodeleeuw** [comment]
I think this is now covered by the Survey plugin.
