### ISSUE TITLE
scroll bars with RDK

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#881]
See #787

**Comment by jodeleeuw** [comment]
Hey @becky-gilbert I didn't check, but does this absolute positioning mean that the canvas element is always in the top left? Does that change the centering behavior of the stimulus at all?

**Comment by becky-gilbert** [comment]
@jodeleeuw I initially had the same concern about this solution. But in the plugin code, the canvas element is set up to have the same width and height as `window.innerWidth` and `window.innerHeight`, which is why scroll bars appear when the canvas has any margin/padding and is positioned anywhere except for (0,0). The dots are centered within the canvas, so they end up being centered in the window as well. I've tested this solution on browsers and window sizes and it works - the stimulus is centered and there are no scroll bars.

However, this does mean that the stimulus doesn't _remain_ centered if the browser is resized after the page loads - if the window gets bigger then the stim will be appear more toward the upper left, and if the window gets smaller then it'll be more toward the bottom/right, and scroll bars will appear. I'm happy to try finding a responsive solution. I don't know if it's possible to responsively resize the canvas itself, but that seems problematic anyway. Another option might be to use a fixed canvas size that's smaller than the typical window, and center the canvas responsively. But I haven't looked at the plugin code closely enough to know if that might cause other problems. Maybe @vrsivananda has some thoughts/suggestions?

**Comment by vrsivananda** [comment]
Hi @becky-gilbert, many apologies for the delayed response. 

Yes, you're right that the canvas size is fixed when the RDK trial begins, and as such it does not re-center when the window resizes. I made it this way as it was intended to not be resized mid-trial. May I know why you might want to resize it mid-trial? There might be another way around the problem, depending on your needs. I can try to help more if I had more context.

If it was for subsequent trials (e.g. resize the window during the instructions, then run the RDK trials after the window has been resized), then [this thread](https://github.com/jspsych/jsPsych/pull/681) might help.

**Comment by becky-gilbert** [comment]
Thanks @vrsivananda! You're right, resizing the browser window after the trial begins isn't really a problem. The bigger issue was removing the scroll bars that appear, and I think that's been resolved now.

The other issue that I wanted to ask about is that the RDK stimulus does not seem to center in the same way as other jsPsych stimuli, but it looks like that's the same issue that's discussed in the thread that you linked to, so thanks for pointing me to that. In the discussion forum question #1122, someone is asking how to center an RDK stimulus relative to an image that's presented separately (the image and RDK stim are overlaid in the post, but that's just to illustrate their relative positioning). This person hasn't found a solution that works across different screen sizes. Please feel free to comment on that discussion thread if you have any suggestions!
